### ISSUE TITLE
使用正常，但是部署则崩溃

### ISSUE THREAD

**Issue by yanhuacuo** [osfans/trime#1220]
复现率 100%

最新 nightly 版 

```
--------- Device Info
OS Name: UKQ1.230804.001 release-keys
OS Version: 6.1.25-android14-11-g92c36beef431-ab11004851 (V816.0.29.0.UNBCNXM)
OS API Level: 34
Device: shennong
Model (product): 23116PN5BC (shennong)
Manufacturer: Xiaomi
Tags: release-keys
Screen Size: 1080 x 2248
Screen Density: 2.625
Screen orientation: Portrait
--------- Build Info
Package Name: com.osfans.trime
Builder: Nightly CI
Version Code: 20240301
Version Name: nightly-0-g5833dba2-release
Build Time: 2024-01-31T16:05:42Z
Build Git Hash: 5833dba2a40730156881b83207967e0311a0f858
--------- Crash stacktrace
java.lang.Exception: Invalid format: The text dictionary contains duplicated keys: ⺓.
	at com.osfans.trime.data.opencc.OpenCCDictManager.openCCDictConv(Native Method)
	at com.osfans.trime.data.opencc.dict.TextDictionary.toOpenCCDictionary(TextDictionary.kt:27)
	at com.osfans.trime.data.opencc.dict.Dictionary.toOpenCCDictionary(Dictionary.kt:41)
	at com.osfans.trime.data.opencc.OpenCCDictManager.buildOpenCCDict(OpenCCDictManager.kt:77)
	at com.osfans.trime.core.Rime$Companion.deploy(Rime.kt:88)
	at com.osfans.trime.ime.core.RimeWrapper.deploy(RimeWrapper.kt:74)
	at com.osfans.trime.ui.main.PrefMainActivity$deploy$1$1.invokeSuspend(PrefMainActivity.kt:154)
	at com.osfans.trime.ui.main.PrefMainActivity$deploy$1$1.invoke(Unknown Source:8)
	at com.osfans.trime.ui.main.PrefMainActivity$deploy$1$1.invoke(Unknown Source:2)
	at com.osfans.trime.util.DialogUtilsKt$rimeActionWithResultDialog$2$result$1.invokeSuspend(DialogUtils.kt:122)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8eb8290, Dispatchers.Main.immediate]

--------- beginning of main
02-01 20:34:56.411 D/ScrollerOptimizationManager(27314): registerConfigChangedListener
02-01 20:34:56.417 I/ViewRootImpl(27314): com.osfans.trime/com.osfans.trime.PrefLauncherAlias use first frame acceleration
02-01 20:34:56.420 I/Choreographer(27314): first vsync insert message into MessageQueue Head
02-01 20:34:56.424 I/rime.trime(27314): engine disposed.
02-01 20:34:56.432 D/VRI[PrefLauncherAlias](27314): vri.reportNextDraw android.view.ViewRootImpl.performTraversals:4277 android.view.ViewRootImpl.doTraversal:2917 android.view.ViewRootImpl$TraversalRunnable.run:10153 android.view.Choreographer$CallbackRecord.run:1615 android.view.Choreographer$CallbackRecord.run:1624 
02-01 20:34:56.432 D/VRI[PrefLauncherAlias](27314): vri.Setup new sync=wmsSync-VRI[PrefLauncherAlias]#98
02-01 20:34:56.432 E/OpenGLRenderer(27314): Unable to match the desired swap behavior.
02-01 20:34:56.437 D/VRI[PrefLauncherAlias](27314): vri.reportDrawFinished
02-01 20:34:56.457 I/rime.trime(27314): writing tsv file: /storage/emulated/0/rime/wubi98_ci.txt
02-01 20:34:56.573 I/[DefaultDispatcher-worker-1](27314): Synced!
02-01 20:34:56.575 I/[DefaultDispatcher-worker-1](27314): Starting up Rime APIs ...
02-01 20:34:56.575 I/rime.trime(27314): registering core components.
02-01 20:34:56.575 I/rime.trime(27314): registering component: config_builder
02-01 20:34:56.575 I/rime.trime(27314): registering component: config
02-01 20:34:56.575 I/rime.trime(27314): registering component: schema
02-01 20:34:56.575 I/rime.trime(27314): registering component: user_config
02-01 20:34:56.575 I/rime.trime(27314): registering components from module 'dict'.
02-01 20:34:56.575 I/rime.trime(27314): registering component: tabledb
02-01 20:34:56.575 I/rime.trime(27314): registering component: stabledb
02-01 20:34:56.575 I/rime.trime(27314): registering component: plain_userdb
02-01 20:34:56.575 I/rime.trime(27314): registering component: userdb
02-01 20:34:56.575 I/rime.trime(27314): registering component: corrector
02-01 20:34:56.575 I/rime.trime(27314): registering component: dictionary
02-01 20:34:56.575 I/rime.trime(27314): registering component: reverse_lookup_dictionary
02-01 20:34:56.575 I/rime.trime(27314): registering component: user_dictionary
02-01 20:34:56.575 I/rime.trime(27314): registering component: userdb_recovery_task
02-01 20:34:56.575 I/rime.trime(27314): registering components from module 'gears'.
02-01 20:34:56.575 I/rime.trime(27314): registering component: ascii_composer
02-01 20:34:56.575 I/rime.trime(27314): registering component: chord_composer
02-01 20:34:56.575 I/rime.trime(27314): registering component: express_editor
02-01 20:34:56.575 I/rime.trime(27314): registering component: fluid_editor
02-01 20:34:56.575 I/rime.trime(27314): registering component: fluency_editor
02-01 20:34:56.575 I/rime.trime(27314): registering component: key_binder
02-01 20:34:56.575 I/rime.trime(27314): registering component: navigator
02-01 20:34:56.575 I/rime.trime(27314): registering component: punctuator
02-01 20:34:56.575 I/rime.trime(27314): registering component: recognizer
02-01 20:34:56.575 I/rime.trime(27314): registering component: selector
02-01 20:34:56.575 I/rime.trime(27314): registering component: speller
02-01 20:34:56.575 I/rime.trime(27314): registering component: shape_processor
02-01 20:34:56.575 I/rime.trime(27314): registering component: abc_segmentor
02-01 20:34:56.575 I/rime.trime(27314): registering component: affix_segmentor
02-01 20:34:56.575 I/rime.trime(27314): registering component: ascii_segmentor
02-01 20:34:56.575 I/rime.trime(27314): registering component: matcher
02-01 20:34:56.575 I/rime.trime(27314): registering component: punct_segmentor
02-01 20:34:56.575 I/rime.trime(27314): registering component: fallback_segmentor
02-01 20:34:56.575 I/rime.trime(27314): registering component: echo_translator
02-01 20:34:56.575 I/rime.trime(27314): registering component: punct_translator
02-01 20:34:56.575 I/rime.trime(27314): registering component: table_translator
02-01 20:34:56.575 I/rime.trime(27314): registering component: script_translator
02-01 20:34:56.575 I/rime.trime(27314): registering component: r10n_translator
02-01 20:34:56.575 I/rime.trime(27314): registering component: reverse_lookup_translator
02-01 20:34:56.575 I/rime.trime(27314): registering component: schema_list_translator
02-01 20:34:56.575 I/rime.trime(27314): registering component: switch_translator
02-01 20:34:56.575 I/rime.trime(27314): registering component: history_translator
02-01 20:34:56.575 I/rime.trime(27314): registering component: simplifier
02-01 20:34:56.575 I/rime.trime(27314): registering component: uniquifier
02-01 20:34:56.575 I/rime.trime(27314): registering component: charset_filter
02-01 20:34:56.576 I/rime.trime(27314): registering component: cjk_minifier
02-01 20:34:56.576 I/rime.trime(27314): registering component: reverse_lookup_filter
02-01 20:34:56.576 I/rime.trime(27314): registering component: single_char_filter
02-01 20:34:56.576 I/rime.trime(27314): registering component: shape_formatter
02-01 20:34:56.576 I/rime.trime(27314): registering component: codepoint_translator
02-01 20:34:56.576 I/rime.trime(27314): registering component: charset_filter
02-01 20:34:56.576 W/rime.trime(27314): replacing previously registered component: charset_filter
02-01 20:34:56.576 I/rime.trime(27314): registering components from module 'lua'.
02-01 20:34:56.579 I/rime.trime(27314): rime.lua info: rime.lua should be either in the rime user data directory or in the rime shared data directory
02-01 20:34:56.579 I/rime.trime(27314): registering component: lua_translator
02-01 20:34:56.579 I/rime.trime(27314): registering component: lua_filter
02-01 20:34:56.579 I/rime.trime(27314): registering component: lua_segmentor
02-01 20:34:56.579 I/rime.trime(27314): registering component: lua_processor
02-01 20:34:56.579 I/rime.trime(27314): registering components from module 'grammar'.
02-01 20:34:56.579 I/rime.trime(27314): registering component: grammar
02-01 20:34:56.579 I/rime.trime(27314): registering component: predictor
02-01 20:34:56.579 I/rime.trime(27314): registering component: predict_translator
02-01 20:34:56.579 I/rime.trime(27314): registering components from module 'levers'.
02-01 20:34:56.579 I/rime.trime(27314): registering component: detect_modifications
02-01 20:34:56.579 I/rime.trime(27314): registering component: installation_update
02-01 20:34:56.579 I/rime.trime(27314): registering component: workspace_update
02-01 20:34:56.579 I/rime.trime(27314): registering component: schema_update
02-01 20:34:56.579 I/rime.trime(27314): registering component: config_file_update
02-01 20:34:56.579 I/rime.trime(27314): registering component: prebuild_all_schemas
02-01 20:34:56.579 I/rime.trime(27314): registering component: user_dict_upgrade
02-01 20:34:56.579 I/rime.trime(27314): registering component: cleanup_trash
02-01 20:34:56.579 I/rime.trime(27314): registering component: user_dict_sync
02-01 20:34:56.579 I/rime.trime(27314): registering component: backup_config_files
02-01 20:34:56.579 I/rime.trime(27314): registering component: clean_old_log_files
02-01 20:34:56.585 I/rime.trime(27314): updating rime installation info.
02-01 20:34:56.585 I/rime.trime(27314): loading config file '/storage/emulated/0/rime/installation.yaml'.
02-01 20:34:56.586 I/rime.trime(27314): installation info exists. installation id: 8f96e7f9-584e-4f89-adc7-9294f3aac614
02-01 20:34:56.586 I/rime.trime(27314): sync dir: /storage/emulated/0/rime/sync
02-01 20:34:56.586 I/rime.trime(27314): previous distribution: trime
02-01 20:34:56.586 I/rime.trime(27314): previous distribution version: nightly-20240131
02-01 20:34:56.586 I/rime.trime(27314): previous Rime version: 1.9.0
02-01 20:34:56.586 I/rime.trime(27314): starting work thread for 3 tasks.
02-01 20:34:56.586 I/rime.trime(27314): running deployment tasks:
02-01 20:34:56.587 I/rime.trime(27314): updating workspace.
02-01 20:34:56.589 I/rime.trime(27314): loading config file '/storage/emulated/0/rime/build/default.yaml'.
02-01 20:34:56.590 I/om.osfans.trime(27314): This is sticky GC, maxfree is 33554432 minfree is 8388608
02-01 20:34:56.594 I/rime.trime(27314): loading config file '/storage/emulated/0/rime/build/default.yaml'.
02-01 20:34:56.596 I/rime.trime(27314): updating schemas.
02-01 20:34:56.596 I/rime.trime(27314): schema: py
02-01 20:34:56.596 I/rime.trime(27314): loading config file '/storage/emulated/0/rime/py.schema.yaml'.
02-01 20:34:56.603 I/rime.trime(27314): loading config file '/storage/emulated/0/rime/build/py.schema.yaml'.
02-01 20:34:56.618 I/rime.trime(27314): loading config file '/storage/emulated/0/rime/build/py.schema.yaml'.
02-01 20:34:56.622 W/System  (27314): A resource failed to call InputEventReceiver.dispose. 
02-01 20:34:56.629 I/rime.trime(27314): preparing dictionary 'py'.
02-01 20:34:56.630 I/rime.trime(27314): compiling dictionary for /storage/emulated/0/rime/build/py.schema.yaml
02-01 20:34:56.645 I/rime.trime(27314): loading table file: /storage/emulated/0/rime/build/py.table.bin
02-01 20:34:56.649 I/rime.trime(27314): loading prism file: /storage/emulated/0/rime/build/py.prism.bin
02-01 20:34:56.649 I/rime.trime(27314): found double array image of size 1792.
02-01 20:34:56.649 I/rime.trime(27314): "/storage/emulated/0/rime/py.dict.yaml"[1 file(s)] (4117753726)
02-01 20:34:56.649 I/rime.trime(27314): /storage/emulated/0/rime/build/py.schema.yaml (3217247531)
02-01 20:34:56.650 I/rime.trime(27314): loading reversedb: /storage/emulated/0/rime/build/py.reverse.bin
02-01 20:34:56.650 I/rime.trime(27314): dictionary 'py' is ready.
02-01 20:34:56.651 I/rime.trime(27314): loading config file '/storage/emulated/0/rime/build/py.schema.yaml'.
02-01 20:34:56.657 I/rime.trime(27314): schema: wubi98_ci
02-01 20:34:56.657 I/rime.trime(27314): loading config file '/storage/emulated/0/rime/wubi98_ci.schema.yaml'.
02-01 20:34:56.662 I/rime.trime(27314): loading config file '/storage/emulated/0/rime/build/wubi98_ci.schema.yaml'.
02-01 20:34:56.669 I/rime.trime(27314): loading config file '/storage/emulated/0/rime/build/wubi98_ci.schema.yaml'.
02-01 20:34:56.676 I/rime.trime(27314): preparing dictionary 'wubi98_ci'.
02-01 20:34:56.676 I/rime.trime(27314): compiling dictionary for /storage/emulated/0/rime/build/wubi98_ci.schema.yaml
02-01 20:34:56.699 I/rime.trime(27314): loading table file: /storage/emulated/0/rime/build/wubi98_ci.table.bin
02-01 20:34:56.702 I/rime.trime(27314): loading prism file: /storage/emulated/0/rime/build/wubi98_ci.prism.bin
02-01 20:34:56.703 I/rime.trime(27314): found double array image of size 181504.
02-01 20:34:56.703 I/rime.trime(27314): "/storage/emulated/0/rime/wubi98_ci.dict.yaml"[1 file(s)] (33630513)
02-01 20:34:56.703 I/rime.trime(27314): /storage/emulated/0/rime/build/wubi98_ci.schema.yaml (2065064760)
02-01 20:34:56.703 I/rime.trime(27314): loading reversedb: /storage/emulated/0/rime/build/wubi98_ci.reverse.bin
02-01 20:34:56.705 I/rime.trime(27314): dictionary 'wubi98_ci' is ready.
02-01 20:34:56.705 I/rime.trime(27314): schema: wubi98_U
02-01 20:34:56.706 I/rime.trime(27314): loading config file '/storage/emulated/0/rime/wubi98_U.schema.yaml'.
02-01 20:34:56.710 I/rime.trime(27314): loading config file '/storage/emulated/0/rime/build/wubi98_U.schema.yaml'.
02-01 20:34:56.723 I/rime.trime(27314): loading config file '/storage/emulated/0/rime/build/wubi98_U.schema.yaml'.
02-01 20:34:56.733 I/rime.trime(27314): preparing dictionary 'wubi98_U'.
02-01 20:34:56.733 I/rime.trime(27314): compiling dictionary for /storage/emulated/0/rime/build/wubi98_U.schema.yaml
02-01 20:34:56.755 I/rime.trime(27314): loading table file: /storage/emulated/0/rime/build/wubi98_U.table.bin
02-01 20:34:56.760 I/rime.trime(27314): loading prism file: /storage/emulated/0/rime/build/wubi98_U.prism.bin
02-01 20:34:56.761 I/rime.trime(27314): found double array image of size 143616.
02-01 20:34:56.761 I/rime.trime(27314): "/storage/emulated/0/rime/wubi98_U.dict.yaml"[1 file(s)] (1449870748)
02-01 20:34:56.761 I/rime.trime(27314): /storage/emulated/0/rime/build/wubi98_U.schema.yaml (2943213301)
02-01 20:34:56.761 I/rime.trime(27314): loading reversedb: /storage/emulated/0/rime/build/wubi98_U.reverse.bin
02-01 20:34:56.763 I/rime.trime(27314): dictionary 'wubi98_U' is ready.
02-01 20:34:56.764 I/rime.trime(27314): loading config file '/storage/emulated/0/rime/build/wubi98_U.schema.yaml'.
02-01 20:34:56.774 I/rime.trime(27314): loading config file '/storage/emulated/0/rime/build/wubi98_ci.schema.yaml'.
02-01 20:34:56.784 I/rime.trime(27314): finished updating schemas: 3 success, 0 failure.
02-01 20:34:56.785 I/rime.trime(27314): loading config file '/storage/emulated/0/rime/user.yaml'.
02-01 20:34:56.788 I/rime.trime(27314): write: var/last_build_time
02-01 20:34:56.788 I/rime.trime(27314): saving config file '/storage/emulated/0/rime/user.yaml'.
02-01 20:34:56.789 I/rime.trime(27314): clean up trash.
02-01 20:34:56.790 I/rime.trime(27314): 3 tasks ran: 3 success, 0 failure.
02-01 20:34:56.790 I/rime.trime(27314): loading config file '/storage/emulated/0/rime/build/default.yaml'.
02-01 20:34:56.793 I/rime.trime(27314): starting engine.
02-01 20:34:56.794 I/rime.trime(27314): loading config file '/storage/emulated/0/rime/user.yaml'.
02-01 20:34:56.794 I/rime.trime(27314): updated option: full_shape
02-01 20:34:56.794 I/rime.trime(27314): updated option: simplification
02-01 20:34:56.795 I/rime.trime(27314): loading config file '/storage/emulated/0/rime/build/wubi98_ci.schema.yaml'.
02-01 20:34:56.806 I/rime.trime(27314): updated option: _auto_commit
02-01 20:34:56.807 I/rime.trime(27314): loading dictionary 'py'.
02-01 20:34:56.807 I/rime.trime(27314): loading table file: /storage/emulated/0/rime/build/py.table.bin
02-01 20:34:56.807 I/rime.trime(27314): loading prism file: /storage/emulated/0/rime/build/py.prism.bin
02-01 20:34:56.808 I/rime.trime(27314): found double array image of size 1792.
02-01 20:34:56.808 I/rime.trime(27314): loading dictionary 'wubi98_ci'.
02-01 20:34:56.808 I/rime.trime(27314): loading table file: /storage/emulated/0/rime/build/wubi98_ci.table.bin
02-01 20:34:56.809 I/rime.trime(27314): loading prism file: /storage/emulated/0/rime/build/wubi98_ci.prism.bin
02-01 20:34:56.810 I/rime.trime(27314): found double array image of size 181504.
02-01 20:34:56.810 I/rime.trime(27314): loading dictionary 'wubi98_ci'.
02-01 20:34:56.810 I/rime.trime(27314): reading tsv file: /storage/emulated/0/rime/wubi98_ci.txt
02-01 20:34:56.813 I/rime.trime(27314): loading reversedb: /storage/emulated/0/rime/build/wubi98_ci.reverse.bin
02-01 20:34:56.814 I/rime.trime(27314): loading dictionary 'wubi98_ci'.
02-01 20:34:56.814 I/rime.trime(27314): loading dictionary 'wubi98_ci'.
02-01 20:34:56.814 I/rime.trime(27314): updated option: ascii_mode
02-01 20:34:56.814 I/rime.trime(27314): updated option: zh_trad
02-01 20:34:56.814 I/rime.trime(27314): updated option: 98wb_spelling
02-01 20:34:56.814 I/[DefaultDispatcher-worker-1](27314): Initializing schema stuffs after starting up ...
02-01 20:34:56.816 I/[DefaultDispatcher-worker-1](27314): Loading config file /storage/emulated/0/rime/build/wubi98_ci.schema.yaml
02-01 20:34:56.975 I/om.osfans.trime(27314): System.exit called, status: 10
02-01 20:34:56.975 I/AndroidRuntime(27314): VM exiting with result code 10, cleanup skipped.
```

**Comment by goofyz** [comment]
似乎是 opencc 的設置問題, 試試將 opencc 回廠一下

**Comment by yanhuacuo** [comment]
> 似乎是 opencc 的設置問題, 試試將 opencc 回廠一下

回厂了，但是还是没有改善

**Comment by shitlime** [comment]
与#1101 相同，opencc的问题，解决方法：

https://github.com/osfans/trime/issues/1101#issuecomment-1800820271

似乎是新版的opencc 对字典文件有了更严格的限制，导致旧版的opencc字典文件大部分都会出现此错误，建议出现此错误时，全部按照这种方法解决

**Comment by yanhuacuo** [comment]
> 与#1101 相同，opencc的问题，解决方法：
> 
> [#1101 (comment)](https://github.com/osfans/trime/issues/1101#issuecomment-1800820271)
> 
> 似乎是新版的opencc 对字典文件有了更严格的限制，导致旧版的opencc字典文件大部分都会出现此错误，建议出现此错误时，全部按照这种方法解决

的确如此
