### ISSUE TITLE
Crash with Koin on LiquidKeyboard

### ISSUE THREAD

**Issue by Bambooin** [osfans/trime#1231]
**Describe the bug**

Random crash on Koin in latest commit of develop.

**To Reproduce**
Steps to reproduce the bug:
4. See bug

**Expected behavior**

**Log**
If applicable, add crash log to quick focus your problem.
```
--------- Crash stacktrace
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	... 1 more
Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for type 'com.osfans.trime.data.theme.Theme'. Check your Modules configuration and add missing type and/or qualifier!
	at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:301)
	at org.koin.core.scope.Scope.resolveValue(Scope.kt:271)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:233)
	at org.koin.core.scope.Scope.get(Scope.kt:212)
	at com.osfans.trime.ime.symbol.LiquidKeyboard$special$$inlined$inject$default$3.invoke(KoinComponent.kt:67)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.osfans.trime.ime.symbol.LiquidKeyboard.getTheme(LiquidKeyboard.kt:39)
	at com.osfans.trime.ime.symbol.LiquidKeyboard.access$getTheme(LiquidKeyboard.kt:36)
	at com.osfans.trime.ime.symbol.LiquidKeyboard$simpleAdapter$2.invoke(LiquidKeyboard.kt:45)
	at com.osfans.trime.ime.symbol.LiquidKeyboard$simpleAdapter$2.invoke(LiquidKeyboard.kt:44)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.osfans.trime.ime.symbol.LiquidKeyboard.getSimpleAdapter(LiquidKeyboard.kt:44)
	at com.osfans.trime.ime.symbol.LiquidKeyboard.initFixData(LiquidKeyboard.kt:141)
	at com.osfans.trime.ime.symbol.LiquidKeyboard.select(LiquidKeyboard.kt:133)
	at com.osfans.trime.ime.core.Trime.selectLiquidKeyboard(Trime.kt:260)
	at com.osfans.trime.ime.core.Trime.selectLiquidKeyboard(Trime.kt:281)
	at com.osfans.trime.ime.text.TextInputManager.onEvent(TextInputManager.kt:347)
	at com.osfans.trime.ime.keyboard.KeyboardView.onLongPress(KeyboardView.kt:1317)
	at com.osfans.trime.ime.keyboard.KeyboardView.openPopupIfRequired(KeyboardView.kt:1294)
	at com.osfans.trime.ime.keyboard.KeyboardView.access$openPopupIfRequired(KeyboardView.kt:63)
	at com.osfans.trime.ime.keyboard.KeyboardView$MyHandler.handleMessage(KeyboardView.kt:329)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	... 3 more
```

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi Mix 4]
 - OS: [e.g. Android 11]
 - Theme: [e.g. Tongwenfeng]
 - Version: [e.g. 3.2.1]
 - Build info: 
   ```
   You could find build info in About Activity and click it to copy.
   e.g. 
   Build: Commit CI
   Date: 2022-06-12 10:09 UTC
   Commit: v3.2.6-58-gd9b4c1f, 2022-06-12 17:58:14 +0800
   Branch: develop
   Repository: https://github.com/osfans/trime
   ```
**Additional context**

**Comment by WhiredPlanck** [comment]
@Bambooin I can't reproduce this issue ......
