### ISSUE TITLE
Random NPE crash in Trime.kt

### ISSUE THREAD

**Issue by Bambooin** [osfans/trime#1243]
**Describe the bug**

Rare random crash.

**To Reproduce**
Steps to reproduce the bug:
4. See bug

**Expected behavior**

**Log**
If applicable, add crash log to quick focus your problem.
```
--------- Crash stacktrace
java.lang.NullPointerException
	at com.osfans.trime.ime.core.Trime.loadConfig(Trime.kt:166)
	at com.osfans.trime.ime.core.Trime.recreateInputView(Trime.kt:316)
	at com.osfans.trime.ime.core.Trime$onThemeChangeListener$1$1.invokeSuspend(Trime.kt:108)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5df48ca, Dispatchers.Main]
```

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi Mix 4]
 - OS: [e.g. Android 11]
 - Theme: [e.g. Tongwenfeng]
 - Version: [e.g. 3.2.1]
 - Build info: 
   ```
   You could find build info in About Activity and click it to copy.
   e.g. 
   Build: Commit CI
   Date: 2022-06-12 10:09 UTC
   Commit: v3.2.6-58-gd9b4c1f, 2022-06-12 17:58:14 +0800
   Branch: develop
   Repository: https://github.com/osfans/trime
   ```
**Additional context**

**Comment by WhiredPlanck** [comment]
Geez, I will look into it.
