### ISSUE TITLE
Random crash with window popup

### ISSUE THREAD

**Issue by Bambooin** [osfans/trime#1301]
**Describe the bug**

**To Reproduce**
Steps to reproduce the bug:
4. See bug

**Expected behavior**

**Log**
If applicable, add crash log to quick focus your problem.
```
--------- Crash stacktrace
java.lang.NullPointerException
	at com.osfans.trime.ime.core.TrimeInputMethodService.loadConfig(TrimeInputMethodService.kt:178)
	at com.osfans.trime.ime.core.TrimeInputMethodService.recreateInputView(TrimeInputMethodService.kt:327)
	at com.osfans.trime.ime.core.TrimeInputMethodService$onColorChangeListener$1$1.invokeSuspend(TrimeInputMethodService.kt:119)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a359735, Dispatchers.Main]

--------- beginning of main
03-18 21:10:25.983 D/WindowTokenClient(18915): Only apply configuration update to Resources because shouldReportConfigChange is false.
03-18 21:10:25.983 D/WindowTokenClient(18915): android.window.WindowTokenClient.attachToDisplayArea:118 android.window.WindowContextController.attachToDisplayArea:107 android.window.WindowProviderService.attachBaseContext:208 android.app.Service.attach:915 android.app.ActivityThread.handleCreateService:4484 
03-18 21:10:26.012 W/Parcel  (18915): Expecting binder but got null!
03-18 21:10:26.022 D/WindowTokenClient(18915): Configuration not dispatch to IME because configuration is up to date. Current config={1.0 460mcc11mnc [en_US] ldltr sw393dp w393dp h798dp 440dpi nrml long port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2340) mAppBounds=Rect(0, 80 - 1080, 2274) mMaxBounds=Rect(0, 0 - 1080, 2340) mDisplayRotation=ROTATION_0 mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} as.47 s.6011 fontWeightAdjustment=0}, reported config={1.0 460mcc11mnc [en_US] ldltr sw393dp w393dp h798dp 440dpi nrml long port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2340) mAppBounds=Rect(0, 80 - 1080, 2274) mMaxBounds=Rect(0, 0 - 1080, 2340) mDisplayRotation=ROTATION_0 mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} as.47 s.6011 fontWeightAdjustment=0}, updated config={1.0 460mcc11mnc [en_US] ldltr sw393dp w393dp h798dp 440dpi nrml long port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2340) mAppBounds=Rect(0, 80 - 1080, 2274) mMaxBounds=Rect(0, 0 - 1080, 2340) mDisplayRotation=ROTATION_0 mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} as.47 s.6011 fontWeightAdjustment=0}
03-19 06:02:06.199 I/om.osfans.trime(18915): System.exit called, status: 10
03-19 06:02:06.199 I/AndroidRuntime(18915): VM exiting with result code 10, cleanup skipped.
```

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi Mix 4]
 - OS: [e.g. Android 11]
 - Theme: [e.g. Tongwenfeng]
 - Version: [e.g. 3.2.1]
 - Build info: 
   ```
   You could find build info in About Activity and click it to copy.
   e.g. 
   --------- Build Info
   Package Name: com.osfans.trime
   Version Code: 20240501
   Version Name: v3.2.17-38-g10660cde-release
   Build Time: 2024-03-16T02:03:45Z
   Build Git Hash: 10660cde02e7d57f3f7def672b2d3375a1bc3b71
   ```
**Additional context**

**Comment by WhiredPlanck** [comment]
https://github.com/osfans/trime/blob/69e8b3adbf7e3ee26ab61e2614e951c7275a509c/app/src/main/java/com/osfans/trime/ime/core/TrimeInputMethodService.kt#L178

`textInputManager` should be called by `.?` instead of `.!!` here. Will fix it soon.
