### ISSUE TITLE
短时间内反复拉起键盘易导致崩溃

### ISSUE THREAD

**Issue by zhumengu** [osfans/trime#1403]
重复打开关闭输入法4次必然会崩溃这个问题在当前4.18后一直有

```
--------- Crash stacktrace
java.lang.IllegalStateException: Dispatcher is not in running state!
	at com.osfans.trime.core.RimeDispatcher.dispatch(RimeDispatcher.kt:128)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:318)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:21)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:168)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at com.osfans.trime.core.Rime.isEmpty(Rime.kt:451)
	at com.osfans.trime.daemon.RimeDaemon$rimeImpl$2$1.isEmpty(Unknown Source:2)
	at com.osfans.trime.ime.text.TextInputManager$onStartInputView$2.invokeSuspend(TextInputManager.kt:220)
	at com.osfans.trime.ime.text.TextInputManager$onStartInputView$2.invoke(Unknown Source:8)
	at com.osfans.trime.ime.text.TextInputManager$onStartInputView$2.invoke(Unknown Source:4)
	at com.osfans.trime.daemon.RimeDaemon$establish$1$run$1$1.invokeSuspend(RimeDaemon.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at com.osfans.trime.daemon.RimeDaemon$establish$1.run(RimeDaemon.kt:60)
	at com.osfans.trime.ime.text.TextInputManager.onStartInputView(TextInputManager.kt:220)
	at com.osfans.trime.ime.core.TrimeInputMethodService$onStartInputView$1$1.invokeSuspend(TrimeInputMethodService.kt:469)
	at com.osfans.trime.ime.core.TrimeInputMethodService$onStartInputView$1$1.invoke(Unknown Source:8)
	at com.osfans.trime.ime.core.TrimeInputMethodService$onStartInputView$1$1.invoke(Unknown Source:4)
	at com.osfans.trime.daemon.RimeDaemon$establish$1$runOnReady$2$1.invokeSuspend(RimeDaemon.kt:65)
	at com.osfans.trime.daemon.RimeDaemon$establish$1$runOnReady$2$1.invoke(Unknown Source:8)
	at com.osfans.trime.daemon.RimeDaemon$establish$1$runOnReady$2$1.invoke(Unknown Source:4)
	at com.osfans.trime.core.RimeLifecycleKt.whenAtState(RimeLifecycle.kt:86)
	at com.osfans.trime.daemon.RimeDaemon$establish$1.runOnReady(RimeDaemon.kt:157)
	at com.osfans.trime.ime.core.TrimeInputMethodService$onStartInputView$1.invokeSuspend(TrimeInputMethodService.kt:465)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8706)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@efc8d14, Dispatchers.Main]
```

**Comment by WhiredPlanck** [comment]
我的第一个问题是：重复打开关闭是指反复收起和弹出键盘吗？

**Comment by zhumengu** [comment]
> 我的第一个问题是：重复打开关闭是指反复收起和弹出键盘吗？

是的

**Comment by WhiredPlanck** [comment]
我这里无法复现。第二个问题是，你所使用的 app 版本号、手机系统版本和型号是什么？

**Comment by zhumengu** [comment]
> 我这里无法复现。第二个问题是，你所使用的 app 版本号、手机系统版本和型号是什么？

版本信息:
构建者：Nightly CI Git 仓库：https://github.com/osfans/trime 构建 Git 哈希：d 0 f1787c8029df4 c4541edf4 a73a 1 a78265bbe6 c 构建时间：2024年6月16日 00:05:30

手机型号:
Redmi Note 12T Pro

系统版本:
Xiaomi Hyper OS
1.0.2.0.ULHCNXM

**Comment by zhumengu** [comment]
报错日志全部

```
--------- Device Info
OS Name: UP1A.231005.007
OS Version: 5.10.168-android12-9-00001-g81e7418c6466-ab10486262 (V816.0.2.0.ULHCNXM)
OS API Level: 34
Device: pearl
Model (product): 23054RA19C (pearl)
Manufacturer: Xiaomi
Tags: release-keys
Screen Size: 1080 x 2316
Screen Density: 2.75
Screen orientation: Portrait
--------- Build Info
Package Name: com.osfans.trime
Builder: Nightly CI
Version Code: 20240701
Version Name: nightly-4-gd0f1787c-release
Build Time: 2024-06-15T16:05:30Z
Build Git Hash: d0f1787c8029df4c4541edf4a73a1a78265bbe6c
--------- Crash stacktrace
kotlin.UninitializedPropertyAccessException: lateinit property activeTheme has not been initialized
	at com.osfans.trime.data.theme.ThemeManager.getActiveTheme(ThemeManager.kt:59)
	at com.osfans.trime.ime.core.InputView.getTheme(InputView.kt:67)
	at com.osfans.trime.ime.core.InputView.<init>(InputView.kt:96)
	at com.osfans.trime.ime.core.TrimeInputMethodService.recreateInputView(TrimeInputMethodService.kt:308)
	at com.osfans.trime.ime.core.TrimeInputMethodService$onCreateInputView$1$1.invokeSuspend(TrimeInputMethodService.kt:431)
	at com.osfans.trime.ime.core.TrimeInputMethodService$onCreateInputView$1$1.invoke(Unknown Source:8)
	at com.osfans.trime.ime.core.TrimeInputMethodService$onCreateInputView$1$1.invoke(Unknown Source:4)
	at com.osfans.trime.daemon.RimeDaemon$establish$1$runOnReady$2$1.invokeSuspend(RimeDaemon.kt:65)
	at com.osfans.trime.daemon.RimeDaemon$establish$1$runOnReady$2$1.invoke(Unknown Source:8)
	at com.osfans.trime.daemon.RimeDaemon$establish$1$runOnReady$2$1.invoke(Unknown Source:4)
	at com.osfans.trime.core.StateDelegate.run(RimeLifecycle.kt:115)
	at com.osfans.trime.core.StateDelegate$run$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8706)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3500dae, Dispatchers.Main]

--------- beginning of main
06-16 18:10:12.011 I/om.osfans.trime(21056): Using CollectorTypeCC GC.
06-16 18:10:12.014 E/om.osfans.trime(21056): Not starting debugger since process cannot load the jdwp agent.
06-16 18:10:12.019 I/MessageMonitor(21056): Load libmiui_runtime
06-16 18:10:12.027 D/CompatibilityChangeReporter(21056): Compat change id reported: 171979766; UID 10340; state: ENABLED
06-16 18:10:12.027 D/CompatibilityChangeReporter(21056): Compat change id reported: 242716250; UID 10340; state: ENABLED
06-16 18:10:12.035 D/nativeloader(21056): Configuring clns-4 for other apk /data/app/~~3-8_oTVAE-zVlEOX0kzw1g==/com.osfans.trime-CCoXiYqEK7ex_QXcey6X_A==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~3-8_oTVAE-zVlEOX0kzw1g==/com.osfans.trime-CCoXiYqEK7ex_QXcey6X_A==/lib/arm64:/data/app/~~3-8_oTVAE-zVlEOX0kzw1g==/com.osfans.trime-CCoXiYqEK7ex_QXcey6X_A==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.osfans.trime
06-16 18:10:12.039 V/GraphicsEnvironment(21056): Currently set values for:
06-16 18:10:12.039 V/GraphicsEnvironment(21056):   angle_gl_driver_selection_pkgs=[]
06-16 18:10:12.039 V/GraphicsEnvironment(21056):   angle_gl_driver_selection_values=[]
06-16 18:10:12.039 V/GraphicsEnvironment(21056): ANGLE GameManagerService for com.osfans.trime: false
06-16 18:10:12.039 V/GraphicsEnvironment(21056): com.osfans.trime is not listed in per-application setting
06-16 18:10:12.039 V/GraphicsEnvironment(21056): App is not on the allowlist for updatable production driver.
06-16 18:10:12.040 I/ForceDarkHelperStubImpl(21056): initialize for com.osfans.trime , ForceDarkOrigin
06-16 18:10:12.041 D/OpenGLRenderer(21056): JNI_OnLoad success
06-16 18:10:12.041 I/MiuiForceDarkConfig(21056): setConfig density:2.750000, mainRule:0, secondaryRule:0, tertiaryRule:0
06-16 18:10:12.045 D/CompatibilityChangeReporter(21056): Compat change id reported: 183155436; UID 10340; state: ENABLED
06-16 18:10:12.069 I/M-ProMotion(21056): M-ProMotion is disabled
06-16 18:10:12.086 I/[rime-main](21056): Starting up Rime APIs ...
06-16 18:10:12.086 I/rime.trime(21056): registering core components.
06-16 18:10:12.086 I/rime.trime(21056): registering component: config_builder
06-16 18:10:12.086 I/rime.trime(21056): registering component: config
06-16 18:10:12.086 I/rime.trime(21056): registering component: schema
06-16 18:10:12.086 I/rime.trime(21056): registering component: user_config
06-16 18:10:12.086 I/rime.trime(21056): registering components from module 'dict'.
06-16 18:10:12.086 I/rime.trime(21056): registering component: tabledb
06-16 18:10:12.086 I/rime.trime(21056): registering component: stabledb
06-16 18:10:12.086 I/rime.trime(21056): registering component: plain_userdb
06-16 18:10:12.086 I/rime.trime(21056): registering component: userdb
06-16 18:10:12.086 I/rime.trime(21056): registering component: corrector
06-16 18:10:12.086 I/rime.trime(21056): registering component: dictionary
06-16 18:10:12.086 I/rime.trime(21056): registering component: reverse_lookup_dictionary
06-16 18:10:12.086 I/rime.trime(21056): registering component: user_dictionary
06-16 18:10:12.086 I/rime.trime(21056): registering component: userdb_recovery_task
06-16 18:10:12.087 I/rime.trime(21056): registering components from module 'gears'.
06-16 18:10:12.087 I/rime.trime(21056): registering component: ascii_composer
06-16 18:10:12.087 I/rime.trime(21056): registering component: chord_composer
06-16 18:10:12.087 I/rime.trime(21056): registering component: express_editor
06-16 18:10:12.087 I/rime.trime(21056): registering component: fluid_editor
06-16 18:10:12.087 I/rime.trime(21056): registering component: fluency_editor
06-16 18:10:12.087 I/rime.trime(21056): registering component: key_binder
06-16 18:10:12.087 I/rime.trime(21056): registering component: navigator
06-16 18:10:12.087 I/rime.trime(21056): registering component: punctuator
06-16 18:10:12.087 I/rime.trime(21056): registering component: recognizer
06-16 18:10:12.087 I/rime.trime(21056): registering component: selector
06-16 18:10:12.087 I/rime.trime(21056): registering component: speller
06-16 18:10:12.087 I/rime.trime(21056): registering component: shape_processor
06-16 18:10:12.087 I/rime.trime(21056): registering component: abc_segmentor
06-16 18:10:12.087 I/rime.trime(21056): registering component: affix_segmentor
06-16 18:10:12.087 I/rime.trime(21056): registering component: ascii_segmentor
06-16 18:10:12.087 I/rime.trime(21056): registering component: matcher
06-16 18:10:12.087 I/rime.trime(21056): registering component: punct_segmentor
06-16 18:10:12.087 I/rime.trime(21056): registering component: fallback_segmentor
06-16 18:10:12.087 I/rime.trime(21056): registering component: echo_translator
06-16 18:10:12.087 I/rime.trime(21056): registering component: punct_translator
06-16 18:10:12.087 I/rime.trime(21056): registering component: table_translator
06-16 18:10:12.087 I/rime.trime(21056): registering component: script_translator
06-16 18:10:12.087 I/rime.trime(21056): registering component: r10n_translator
06-16 18:10:12.087 I/rime.trime(21056): registering component: reverse_lookup_translator
06-16 18:10:12.087 I/rime.trime(21056): registering component: schema_list_translator
06-16 18:10:12.087 I/rime.trime(21056): registering component: switch_translator
06-16 18:10:12.087 I/rime.trime(21056): registering component: history_translator
06-16 18:10:12.087 I/rime.trime(21056): registering component: simplifier
06-16 18:10:12.087 I/rime.trime(21056): registering component: uniquifier
06-16 18:10:12.087 I/rime.trime(21056): registering component: charset_filter
06-16 18:10:12.087 I/rime.trime(21056): registering component: cjk_minifier
06-16 18:10:12.087 I/rime.trime(21056): registering component: reverse_lookup_filter
06-16 18:10:12.087 I/rime.trime(21056): registering component: single_char_filter
06-16 18:10:12.087 I/rime.trime(21056): registering component: shape_formatter
06-16 18:10:12.087 I/rime.trime(21056): registering component: codepoint_translator
06-16 18:10:12.087 I/rime.trime(21056): registering component: charset_filter
06-16 18:10:12.087 W/rime.trime(21056): replacing previously registered component: charset_filter
06-16 18:10:12.087 I/rime.trime(21056): registering components from module 'lua'.
06-16 18:10:12.089 I/rime.trime(21056): registering component: lua_translator
06-16 18:10:12.089 I/rime.trime(21056): registering component: lua_filter
06-16 18:10:12.089 I/rime.trime(21056): registering component: lua_segmentor
06-16 18:10:12.089 I/rime.trime(21056): registering component: lua_processor
06-16 18:10:12.089 I/rime.trime(21056): registering components from module 'grammar'.
06-16 18:10:12.089 I/rime.trime(21056): registering component: grammar
06-16 18:10:12.089 I/rime.trime(21056): registering component: predictor
06-16 18:10:12.089 I/rime.trime(21056): registering component: predict_translator
06-16 18:10:12.089 I/rime.trime(21056): registering components from module 'levers'.
06-16 18:10:12.089 I/rime.trime(21056): registering component: detect_modifications
06-16 18:10:12.089 I/rime.trime(21056): registering component: installation_update
06-16 18:10:12.089 I/rime.trime(21056): registering component: workspace_update
06-16 18:10:12.089 I/rime.trime(21056): registering component: schema_update
06-16 18:10:12.089 I/rime.trime(21056): registering component: config_file_update
06-16 18:10:12.089 I/rime.trime(21056): registering component: prebuild_all_schemas
06-16 18:10:12.089 I/rime.trime(21056): registering component: user_dict_upgrade
06-16 18:10:12.089 I/rime.trime(21056): registering component: cleanup_trash
06-16 18:10:12.089 I/rime.trime(21056): registering component: user_dict_sync
06-16 18:10:12.089 I/rime.trime(21056): registering component: backup_config_files
06-16 18:10:12.089 I/rime.trime(21056): registering component: clean_old_log_files
06-16 18:10:12.090 W/rime.trime(21056): couldn't list directory './': filesystem error: in directory_iterator::directory_iterator(...): Permission denied [./]
06-16 18:10:12.090 I/rime.trime(21056): updating rime installation info.
06-16 18:10:12.090 I/rime.trime(21056): loading config file '/storage/emulated/0/rime/installation.yaml'.
06-16 18:10:12.091 I/rime.trime(21056): installation info exists. installation id: Redmi
06-16 18:10:12.091 I/rime.trime(21056): sync dir: /storage/emulated/0/RimeSync
06-16 18:10:12.091 I/rime.trime(21056): previous distribution: trime
06-16 18:10:12.091 I/rime.trime(21056): previous distribution version: nightly-4-gd0f1787c
06-16 18:10:12.091 I/rime.trime(21056): previous Rime version: 1.11.2
06-16 18:10:12.094 I/rime.trime(21056): loading config file '/storage/emulated/0/rime/user.yaml'.
06-16 18:10:12.094 I/rime.trime(21056): modifications detected. workspace needs update.
06-16 18:10:12.094 I/rime.trime(21056): changes detected; starting maintenance.
06-16 18:10:12.094 I/rime.trime(21056): starting work thread for 3 tasks.
06-16 18:10:12.094 I/rime.trime(21056): running deployment tasks:
06-16 18:10:12.095 I/rime.trime(21056): updating workspace.
06-16 18:10:12.096 I/rime.trime(21056): loading config file '/storage/emulated/0/rime/build/default.yaml'.
06-16 18:10:12.099 I/SurfaceFactory(21056): [static] sSurfaceFactory = com.mediatek.view.impl.SurfaceFactoryImpl@803ffe2
06-16 18:10:12.100 D/CompatibilityChangeReporter(21056): Compat change id reported: 237531167; UID 10340; state: DISABLED
06-16 18:10:12.105 I/rime.trime(21056): loading config file '/storage/emulated/0/rime/build/default.yaml'.
06-16 18:10:12.108 W/libc    (21056): Access denied finding property "ro.vendor.display.iris_x7.support"
06-16 18:10:12.111 D/VRI[InputMethod](21056): hardware acceleration = true, forceHwAccelerated = false
06-16 18:10:12.113 I/rime.trime(21056): updating schemas.
06-16 18:10:12.113 I/rime.trime(21056): schema: luna_pinyin
06-16 18:10:12.114 I/rime.trime(21056): loading config file '/storage/emulated/0/rime/luna_pinyin.schema.yaml'.
06-16 18:10:12.116 I/rime.trime(21056): loading config file '/storage/emulated/0/rime/build/luna_pinyin.schema.yaml'.
06-16 18:10:12.118 D/libMEOW (21056): meow new tls: 0xb400007d6f0b9d00
06-16 18:10:12.118 D/libMEOW (21056): meow reload base cfg path: na
06-16 18:10:12.118 D/libMEOW (21056): meow reload overlay cfg path: na
06-16 18:10:12.118 W/QT      (21056): qt_process_init() called
06-16 18:10:12.118 E/QT      (21056): [QT]file does not exist
06-16 18:10:12.118 W/QT      (21056): Support!!
06-16 18:10:12.118 E/QT      (21056): [QT]file does not exist
06-16 18:10:12.119 D/libMEOW (21056): applied 1 plugins for [com.osfans.trime]:
06-16 18:10:12.119 D/libMEOW (21056):   plugin 1: [libMEOW_gift.so]:
06-16 18:10:12.128 W/MiuiStubRegistry(21056): Failed to collect stub providers in android.magicpointer.util.MiuiMagicPointerUtilsStubHeadManifest$$: /system_ext/framework/miui-framework-pointer-pad.jar not exist
06-16 18:10:12.132 V/InputMethod(21056): IMS.showSoftInput()
06-16 18:10:12.135 D/CompatibilityChangeReporter(21056): Compat change id reported: 210923482; UID 10340; state: ENABLED
06-16 18:10:12.142 I/rime.trime(21056): loading config file '/storage/emulated/0/rime/build/luna_pinyin.schema.yaml'.
06-16 18:10:12.145 I/[main]  (21056): onWindowShown...
06-16 18:10:12.159 I/rime.trime(21056): preparing dictionary 'luna_pinyin.extended'.
06-16 18:10:12.160 I/rime.trime(21056): compiling dictionary for /storage/emulated/0/rime/build/luna_pinyin.schema.yaml
06-16 18:10:12.167 D/BufferQueueConsumer(21056): [](id:524000000000,api:0,p:-1,c:21056) connect: controlledByApp=false
06-16 18:10:12.172 D/libMEOW (21056): meow new tls: 0xb400007d61529780
06-16 18:10:12.173 D/libMEOW (21056): applied 1 plugins for [com.osfans.trime]:
06-16 18:10:12.173 D/libMEOW (21056):   plugin 1: [libMEOW_gift.so]:
06-16 18:10:12.173 D/VRI[InputMethod](21056): vri.reportNextDraw android.view.ViewRootImpl.performTraversals:4376 android.view.ViewRootImpl.doTraversal:2992 android.view.ViewRootImpl$TraversalRunnable.run:10469 android.view.Choreographer$CallbackRecord.run:1671 android.view.Choreographer$CallbackRecord.run:1680 
06-16 18:10:12.174 D/VRI[InputMethod](21056): vri.Setup new sync=wmsSync-VRI[InputMethod]#0
06-16 18:10:12.204 W/libc    (21056): Access denied finding property "vendor.migl.debug"
06-16 18:10:12.205 E/libMiGL (21056): libmigl:This GPU version is note support Variable Shading Rate
06-16 18:10:12.209 E/libEGL  (21056): pre_cache appList: com.sina.weibo,com.ss.android.article.news,com.taobao.taobao,com.smile.gifmaker,com.ss.android.ugc.aweme,com.tencent.mm,tv.danmaku.bili,,,,,
06-16 18:10:12.214 E/OpenGLRenderer(21056): Unable to match the desired swap behavior.
06-16 18:10:12.216 W/AnimatedVectorDrawable(21056): Duration for the animation is too long :2000, the animation will subsample the keyframe or path data.
06-16 18:10:12.216 W/AnimatedVectorDrawable(21056): Duration for the animation is too long :2000, the animation will subsample the keyframe or path data.
06-16 18:10:12.216 W/AnimatedVectorDrawable(21056): Duration for the animation is too long :2000, the animation will subsample the keyframe or path data.
06-16 18:10:12.217 W/AnimatedVectorDrawable(21056): Duration for the animation is too long :2000, the animation will subsample the keyframe or path data.
06-16 18:10:12.218 W/libc    (21056): Access denied finding property "ro.vendor.display.iris_x7.support"
06-16 18:10:12.218 D/OpenGLRenderer(21056): makeCurrent grContext:0xb400007d580cf0e0 reset mTextureAvailable
06-16 18:10:12.219 D/om.osfans.trime(21056): MiuiProcessManagerServiceStub setSchedFifo
06-16 18:10:12.219 I/MiuiProcessManagerImpl(21056): setSchedFifo pid:21056, mode:3
06-16 18:10:12.222 W/libc    (21056): Access denied finding property "ro.vendor.magt.mtk_magt_support"
06-16 18:10:12.222 D/MAGT_SYNC_FRAME(21056): MAGT Sync: MAGT is not supported. Disabling Sync.
06-16 18:10:12.225 W/libc    (21056): Access denied finding property "ro.vendor.display.iris_x7.support"
06-16 18:10:12.245 E/LB      (21056): fail to open file: No such file or directory
06-16 18:10:12.245 E/LB      (21056): fail to open node: No such file or directory
06-16 18:10:12.246 W/libc    (21056): Access denied finding property "ro.vendor.display.iris_x7.support"
06-16 18:10:12.246 D/BLASTBufferQueue(21056): [VRI[InputMethod]#0](f:0,a:1) acquireNextBufferLocked size=1080x2360 mFrameNumber=1 applyTransaction=true mTimestamp=607459345075822(auto) mPendingTransactions.size=0 graphicBufferId=90434831384576 transform=0
06-16 18:10:12.247 D/VRI[InputMethod](21056): vri.reportDrawFinished
06-16 18:10:12.248 D/VRI[InputMethod](21056): vri.reportNextDraw android.view.ViewRootImpl.handleResized:2309 android.view.ViewRootImpl.-$$Nest$mhandleResized:0 android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl:6745 android.view.ViewRootImpl$ViewRootHandler.handleMessage:6714 android.os.Handler.dispatchMessage:106 
06-16 18:10:12.249 D/VRI[InputMethod](21056): vri.Setup new sync=wmsSync-VRI[InputMethod]#2
06-16 18:10:12.252 D/VRI[InputMethod](21056): vri.reportDrawFinished
06-16 18:10:12.451 I/rime.trime(21056): loading table file: /storage/emulated/0/rime/build/luna_pinyin.extended.table.bin
06-16 18:10:12.456 I/rime.trime(21056): loading prism file: /storage/emulated/0/rime/build/luna_pinyin.extended.prism.bin
06-16 18:10:12.456 I/rime.trime(21056): found double array image of size 1792.
06-16 18:10:12.456 I/rime.trime(21056): /storage/emulated/0/rime/luna_pinyin.extended.dict.yaml[3 file(s)] (3519341445)
06-16 18:10:12.456 I/rime.trime(21056): /storage/emulated/0/rime/build/luna_pinyin.schema.yaml (978711554)
06-16 18:10:12.457 I/rime.trime(21056): loading reversedb: /storage/emulated/0/rime/build/luna_pinyin.extended.reverse.bin
06-16 18:10:12.458 I/rime.trime(21056): dictionary 'luna_pinyin.extended' is ready.
06-16 18:10:12.461 I/rime.trime(21056): loading config file '/storage/emulated/0/rime/build/luna_pinyin.schema.yaml'.
06-16 18:10:12.470 I/rime.trime(21056): finished updating schemas: 1 success, 0 failure.
06-16 18:10:12.470 I/rime.trime(21056): loading config file '/storage/emulated/0/rime/user.yaml'.
06-16 18:10:12.471 I/rime.trime(21056): write: var/last_build_time
06-16 18:10:12.471 I/rime.trime(21056): saving config file '/storage/emulated/0/rime/user.yaml'.
06-16 18:10:12.473 I/rime.trime(21056): clean up trash.
06-16 18:10:12.473 I/rime.trime(21056): 3 tasks ran: 3 success, 0 failure.
06-16 18:10:12.474 I/rime.trime(21056): loading config file '/storage/emulated/0/rime/build/default.yaml'.
06-16 18:10:12.476 I/rime.trime(21056): starting engine.
06-16 18:10:12.476 I/rime.trime(21056): loading config file '/storage/emulated/0/rime/user.yaml'.
06-16 18:10:12.476 I/rime.trime(21056): updated option: ascii_punct
06-16 18:10:12.477 I/rime.trime(21056): updated option: full_shape
06-16 18:10:12.477 I/rime.trime(21056): updated option: simplification
06-16 18:10:12.477 I/rime.trime(21056): loading config file '/storage/emulated/0/rime/build/luna_pinyin.schema.yaml'.
06-16 18:10:12.488 I/rime.trime(21056): updated option: _auto_commit
06-16 18:10:12.488 I/rime.trime(21056): reading tsv file: /storage/emulated/0/rime/custom_phrase.txt
06-16 18:10:12.489 W/rime.trime(21056): invalid metadata at line 3 in file: /storage/emulated/0/rime/custom_phrase.txt.
06-16 18:10:12.489 W/rime.trime(21056): invalid metadata at line 4 in file: /storage/emulated/0/rime/custom_phrase.txt.
06-16 18:10:12.490 I/rime.trime(21056): loading dictionary 'luna_pinyin.extended'.
06-16 18:10:12.490 I/rime.trime(21056): loading table file: /storage/emulated/0/rime/build/luna_pinyin.extended.table.bin
06-16 18:10:12.500 I/rime.trime(21056): loading prism file: /storage/emulated/0/rime/build/luna_pinyin.extended.prism.bin
06-16 18:10:12.500 I/rime.trime(21056): found double array image of size 1792.
06-16 18:10:12.549 I/rime.trime(21056): ConcreteEngine::InitializeOptions
06-16 18:10:12.549 I/rime.trime(21056): found switch option: ascii_mode, reset: 0
06-16 18:10:12.549 I/rime.trime(21056): updated option: ascii_mode
06-16 18:10:12.549 I/rime.trime(21056): found switch option: full_shape, reset: -1
06-16 18:10:12.549 I/rime.trime(21056): found switch option: simplification, reset: -1
06-16 18:10:12.549 I/rime.trime(21056): found switch option: ascii_punct, reset: -1
06-16 18:10:12.550 I/[rime-main](21056): Loading config file /storage/emulated/0/rime/build/default.yaml
06-16 18:10:12.571 I/[rime-main](21056): Loading config file /storage/emulated/0/rime/build/luna_pinyin.schema.yaml
06-16 18:10:12.927 I/om.osfans.trime(21056): System.exit called, status: 10
06-16 18:10:12.927 I/AndroidRuntime(21056): VM exiting with result code 10, cleanup skipped.
```

**Comment by WhiredPlanck** [comment]
你使用的主题是？

**Comment by zhumengu** [comment]
> 你使用的主题是？

使用任何主题与配色都会出现崩溃

**Comment by WhiredPlanck** [comment]
> > 你使用的主题是？
> 
> 使用任何主题与配色都会出现崩溃

我装的也是这个版本，实在无法复现 ......

**Comment by zhumengu** [comment]
> > > 你使用的主题是？
> > 
> > 使用任何主题与配色都会出现崩溃
> 
> 我装的也是这个版本，实在无法复现 ......

问题出现在打开后台配置同步选项时,这里的逻辑可能有问题

**Comment by zzndb** [comment]
> lateinit property activeTheme has not been initialized

这个报错在我这儿可以通过这样复现
- 杀掉程序进程
- 找个输入框拉起键盘

如果没有报错多来几次就能复现
我现在版本是之前自己编译的这个 d0ecf5cc2e14f923607c8d2620eaa1ec9d29ccd0 commit
