### ISSUE TITLE
Crash on selecting schema in setting

### ISSUE THREAD

**Issue by Bambooin** [osfans/trime#430]
1. Clean install last commit build
2. Install rimerc from https://github.com/Bambooin/rimerc/releases/tag/0.1.0
3. Select Input -> Schemas, tirme crash
4. Version 3.2.1 is good for rimerc config

**Comment by Bambooin** [comment]
Logcat:

```
06-19 17:36:19.370 19094 19094 D AndroidRuntime: Shutting down VM
06-19 17:36:19.370 19094 19094 E AndroidRuntime: FATAL EXCEPTION: main
06-19 17:36:19.370 19094 19094 E AndroidRuntime: Process: com.osfans.trime, PID: 19094
06-19 17:36:19.370 19094 19094 E AndroidRuntime: kotlin.UninitializedPropertyAccessException: lateinit property schemaNames has not been initialized
06-19 17:36:19.370 19094 19094 E AndroidRuntime:        at com.osfans.trime.settings.components.SchemaPickerDialog.<init>(SchemaPickerDialog.kt:69)
06-19 17:36:19.370 19094 19094 E AndroidRuntime:        at com.osfans.trime.Pref.onPreferenceTreeClick(Pref.java:309)
06-19 17:36:19.370 19094 19094 E AndroidRuntime:        at android.preference.Preference.performClick(Preference.java:1146)
06-19 17:36:19.370 19094 19094 E AndroidRuntime:        at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:249)
06-19 17:36:19.370 19094 19094 E AndroidRuntime:        at android.widget.AdapterView.performItemClick(AdapterView.java:318)
06-19 17:36:19.370 19094 19094 E AndroidRuntime:        at android.widget.AbsListView.performItemClick(AbsListView.java:1159)
06-19 17:36:19.370 19094 19094 E AndroidRuntime:        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
06-19 17:36:19.370 19094 19094 E AndroidRuntime:        at android.widget.AbsListView$3.run(AbsListView.java:4052)
06-19 17:36:19.370 19094 19094 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
06-19 17:36:19.370 19094 19094 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
06-19 17:36:19.370 19094 19094 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
06-19 17:36:19.370 19094 19094 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6718)
06-19 17:36:19.370 19094 19094 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-19 17:36:19.370 19094 19094 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
06-19 17:36:19.370 19094 19094 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
06-19 17:36:19.376  1318  2877 W ActivityManager:   Force finishing activity com.osfans.trime/.Pref
06-19 17:36:19.394 19094 19094 I Process : Sending signal. PID: 19094 SIG: 9
```

**Comment by WhiredPlanck** [comment]
It may caused by the incorrect initializing method for variable, it's my fault, I'll take care of it. Thanks for your feedback. :+1:

**Comment by WhiredPlanck** [comment]
问题已经找到了，稍后 PR 补充说明。

**Comment by WhiredPlanck** [comment]
#435 将会修复此问题。发生的原因在于 `schemaNames` 是个稍后初始化的变量，然而原来在其还未被初始化的情况下，先初始化了 `pickerDialogBuilder` 对话框构建器并调用了它，导致报错。

另外在键盘上调用对话框时，要为 `pickerDialog` 附加窗口参数，否则会显示不出来，并导致选择/设定失败。原来的写法难以在 `Trime` 服务里附加，所以转而交由类自己承担这一任务。同理，也为 `ThemePickerDialog` 进行了类似的处理。 :smiley:
