### ISSUE TITLE
lenovo J606F无法使用输入法

### ISSUE THREAD

**Issue by langyxxl** [osfans/trime#632]
**Describe the bug**

**To Reproduce**
Steps to reproduce the bug:
1. 安装最新的trime3.2.3
2. 打开trime，点击部署
3. 打开其他应用输入框

**Expected behavior**
有键盘弹出

**Log**
adb 的log中过滤trime，得到如下：
12-16 17:49:49.860  6345  6345 I ZuiResourcesLog: ExtraResources; getZuiDrawable; packageName = com.osfans.trime,resid = 2131623936,density 0
12-16 17:49:49.862  6345  6345 I ZuiResourcesLog: ThemeIconResources; getThemeIconDrawable; packageName com.osfans.trime,original resource path = res/q5.xml
12-16 17:49:49.863  1364  1402 I ZuiResourcesLog: AppIconThemeServices; getThemeIconInfo; inPackageName = com.osfans.trime,inResoucePath = res/q5.xml
12-16 17:49:49.863  1364  1402 I ZuiResourcesLog: AppIconThemeServices; getThemeIconInfoByFileName; iconMapName = com_osfans_trime__q5,density 240
12-16 17:49:49.863  6345  6345 I ZuiResourcesLog: ThemeIconResources; getThemeIconInfo; themeIconInfo: com_osfans_trime__q5;;;;105;105
12-16 17:49:49.869  6345  6345 D ZuiResourcesLog: ExtraResources; getDrawableForDensity;  dr != null putCachedIcon name {ResourceName com.osfans.trime / 2131623936}
12-16 17:49:50.251  6345  6345 E AndroidRuntime: Process: com.osfans.trime, PID: 6345
12-16 17:49:50.251  6345  6345 E AndroidRuntime: java.lang.IllegalArgumentException: No enum constant com.osfans.trime.ime.landscapeinput.LandscapeInputUIMode.PREVIEW
12-16 17:49:50.251  6345  6345 E AndroidRuntime: 	at com.osfans.trime.ime.landscapeinput.LandscapeInputUIMode.valueOf(Unknown Source:2)
12-16 17:49:50.251  6345  6345 E AndroidRuntime: 	at com.osfans.trime.ime.landscapeinput.LandscapeInputUIMode$Companion.fromString(LandscapeInputUIMode.kt:10)
12-16 17:49:50.251  6345  6345 E AndroidRuntime: 	at com.osfans.trime.ime.core.Preferences$Keyboard.getFullscreenMode(Preferences.kt:191)
12-16 17:49:50.251  6345  6345 E AndroidRuntime: 	at com.osfans.trime.ime.core.Trime.onEvaluateFullscreenMode(Trime.java:1480)
12-16 17:49:50.251  6345  6345 E AndroidRuntime: 	at com.osfans.trime.ime.core.Trime.updateFullscreenMode(Trime.java:1498)
12-16 17:49:50.251  6345  6345 E AndroidRuntime: 	at com.osfans.trime.ime.core.Trime.showWindow(Trime.java:757)
12-16 17:49:50.325  1364  1888 I ActivityManager: Process com.osfans.trime (pid 6345) has died: vis FGSL
12-16 17:49:50.326  1364  1888 W ActivityManager: Scheduling restart of crashed service com.osfans.trime/.TrimeImeService in 1800000ms

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: lenove j606f
 - OS: android10
 - Version: 3.2.3
 - Theme: 默认

**Additional context**

**Comment by langyxxl** [comment]
找到原因了，需要在设置里面把
横屏时全屏编辑为auto
