### ISSUE TITLE
Crash when I copy some text

### ISSUE THREAD

**Issue by linsui** [osfans/trime#785]
**Describe the bug**
When I copy some text, e.g. the crash log of trime, trime crashes.

**To Reproduce**
Steps to reproduce the bug:
1. Copy some text
2. Crashes

**Expected behavior**
Don't crash

**Log**

```
FATAL EXCEPTION: main
Process: com.osfans.trime, PID: 16112
java.lang.NullPointerException: Attempt to invoke virtual method '[java.io](http://java.io/).File android.content.Context.getDatabasePath(java.lang.String)' on a null object reference
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked([SQLiteOpenHelper.java:370](http://sqliteopenhelper.java:370/))
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase([SQLiteOpenHelper.java:316](http://sqliteopenhelper.java:316/))
	at com.osfans.trime.clipboard.ClipboardDao.add([ClipboardDao.java:44](http://clipboarddao.java:44/))
	at com.osfans.trime.ime.symbol.LiquidKeyboard.addClipboardData([LiquidKeyboard.java:71](http://liquidkeyboard.java:71/))
	at com.osfans.trime.ime.core.Trime.lambda$clipBoardMonitor$5$com-osfans-trime-ime-core-Trime([Trime.java:1253](http://trime.java:1253/))
	at com.osfans.trime.ime.core.Trime$$ExternalSyntheticLambda0.onPrimaryClipChanged(Unknown Source:6)
	at android.content.ClipboardManager.reportPrimaryClipChanged([ClipboardManager.java:250](http://clipboardmanager.java:250/))
	at android.content.ClipboardManager$1.lambda$dispatchPrimaryClipChanged$0$ClipboardManager$1([ClipboardManager.java:62](http://clipboardmanager.java:62/))
	at android.content.-$$Lambda$ClipboardManager$1$hQk8olbGAgUi4WWNG4ZuDZsM39s.run(Unknown Source:2)
	at android.os.Handler.handleCallback([Handler.java:938](http://handler.java:938/))
	at android.os.Handler.dispatchMessage([Handler.java:99](http://handler.java:99/))
	at android.os.Looper.loop([Looper.java:223](http://looper.java:223/))
	at [android.app](http://android.app/).ActivityThread.main([ActivityThread.java:7664](http://activitythread.java:7664/))
	at java.lang.reflect.Method.invoke(Native Method)
	at [com.android](http://com.android/).internal.os.RuntimeInit$MethodAndArgsCaller.run([RuntimeInit.java:592](http://runtimeinit.java:592/))
	at [com.android](http://com.android/).internal.os.ZygoteInit.main([ZygoteInit.java:947](http://zygoteinit.java:947/))
```

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Mi 6
 - OS: Android 11
 - Version: 3.2.6
 - Theme: Default

**Comment by tumuyan** [comment]
What theme do you use? please reset trime.yaml and try default theme.

**Comment by linsui** [comment]
I'm using the Dark Temple theme. With the default theme it still crashes.

**Comment by linsui** [comment]
```
--------- beginning of main
W/TextToSpeech(14453): stop failed: not bound to TTS engine
I/System.out(14453):  165 165 165 165
I/System.out(14453):  182 182 182 184
I/System.out(14453):  132 132 132 132 132
I/System.out(14453):  145 145 145 145 146
I/System.out(14453):  132 132 132 132 132
I/System.out(14453):  145 145 145 145 146
I/System.out(14453):  132 132 132 132 132
I/System.out(14453):  145 145 145 145 146
E/ThemeUtils(14453): View class com.osfans.trime.ime.text.Composition is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
I/System.out(14453):  165 165 165 165
I/System.out(14453):  182 182 182 184
I/System.out(14453):  132 132 132 132 132
I/System.out(14453):  145 145 145 145 146
I/System.out(14453):  132 132 132 132 132
I/System.out(14453):  145 145 145 145 146
I/System.out(14453):  132 132 132 132 132
I/System.out(14453):  145 145 145 145 146
I/System.out(14453):  165 165 165 165
I/System.out(14453):  182 182 182 184
I/System.out(14453):  132 132 132 132 132
I/System.out(14453):  145 145 145 145 146
I/System.out(14453):  132 132 132 132 132
I/System.out(14453):  145 145 145 145 146
I/System.out(14453):  132 132 132 132 132
I/System.out(14453):  145 145 145 145 146
D/ActivityThread(14453): ViewRootImpl.ConfigChangedCallback for IME, config={1.0 460mcc1mnc [zh_CN,en_US] ldltr sw360dp w360dp h616dp 480dpi nrml long port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 1920) mAppBounds=Rect(0, 0 - 1080, 1920) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} s.1272}
I/Adreno  (14453): QUALCOMM build                   : 2c6a1c7, I1490fecf6e
I/Adreno  (14453): Build Date                       : 02/04/19
I/Adreno  (14453): OpenGL ES Shader Compiler Version: EV031.25.03.02
I/Adreno  (14453): Local Branch                     : 
I/Adreno  (14453): Remote Branch                    : 
I/Adreno  (14453): Remote Branch                    : 
I/Adreno  (14453): Reconstruct Branch               : 
I/Adreno  (14453): Build Config                     : S L 6.0.7 AArch64
I/Adreno  (14453): PFP: 0x005ff112, ME: 0x005ff066
E/libEGL  (14453): Driver indicates EGL 1.5 support, but does not have a critical API
I/Gralloc4(14453): mapper 4.x is not supported
W/Gralloc3(14453): mapper 3.x is not supported
D/ActivityThread(14453): ViewRootImpl.ConfigChangedCallback for IME, config={1.0 460mcc1mnc [zh_CN,en_US] ldltr sw360dp w360dp h616dp 480dpi nrml long port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 1920) mAppBounds=Rect(0, 0 - 1080, 1920) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} s.1272}
D/ActivityThread(14453): ViewRootImpl.ConfigChangedCallback for IME, config={1.0 460mcc1mnc [zh_CN,en_US] ldltr sw360dp w360dp h616dp 480dpi nrml long port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 1920) mAppBounds=Rect(0, 0 - 1080, 1920) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} s.1272}
D/ActivityThread(14453): ViewRootImpl.ConfigChangedCallback for IME, config={1.0 460mcc1mnc [zh_CN,en_US] ldltr sw360dp w360dp h616dp 480dpi nrml long port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 1920) mAppBounds=Rect(0, 0 - 1080, 1920) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} s.1272}
W/TextToSpeech(14453): stop failed: not bound to TTS engine
D/AndroidRuntime(14453): Shutting down VM
--------- beginning of crash
E/AndroidRuntime(14453): FATAL EXCEPTION: main
E/AndroidRuntime(14453): Process: com.osfans.trime, PID: 14453
E/AndroidRuntime(14453): java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.content.Context.getDatabasePath(java.lang.String)' on a null object reference
E/AndroidRuntime(14453): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:370)
E/AndroidRuntime(14453): 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
E/AndroidRuntime(14453): 	at com.osfans.trime.data.db.clipboard.ClipboardDao.add(ClipboardDao.java:44)
E/AndroidRuntime(14453): 	at com.osfans.trime.ime.symbol.LiquidKeyboard.addClipboardData(LiquidKeyboard.java:73)
E/AndroidRuntime(14453): 	at com.osfans.trime.ime.core.Trime.lambda$clipBoardMonitor$5$com-osfans-trime-ime-core-Trime(Trime.java:1472)
E/AndroidRuntime(14453): 	at com.osfans.trime.ime.core.Trime$$ExternalSyntheticLambda0.onPrimaryClipChanged(Unknown Source:6)
E/AndroidRuntime(14453): 	at android.content.ClipboardManager.reportPrimaryClipChanged(ClipboardManager.java:250)
E/AndroidRuntime(14453): 	at android.content.ClipboardManager$1.lambda$dispatchPrimaryClipChanged$0$ClipboardManager$1(ClipboardManager.java:62)
E/AndroidRuntime(14453): 	at android.content.-$$Lambda$ClipboardManager$1$hQk8olbGAgUi4WWNG4ZuDZsM39s.run(Unknown Source:2)
E/AndroidRuntime(14453): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(14453): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(14453): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(14453): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
E/AndroidRuntime(14453): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14453): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(14453): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/CustomActivityOnCrash(14453): App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
E/CustomActivityOnCrash(14453): java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.content.Context.getDatabasePath(java.lang.String)' on a null object reference
E/CustomActivityOnCrash(14453): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:370)
E/CustomActivityOnCrash(14453): 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
E/CustomActivityOnCrash(14453): 	at com.osfans.trime.data.db.clipboard.ClipboardDao.add(ClipboardDao.java:44)
E/CustomActivityOnCrash(14453): 	at com.osfans.trime.ime.symbol.LiquidKeyboard.addClipboardData(LiquidKeyboard.java:73)
E/CustomActivityOnCrash(14453): 	at com.osfans.trime.ime.core.Trime.lambda$clipBoardMonitor$5$com-osfans-trime-ime-core-Trime(Trime.java:1472)
E/CustomActivityOnCrash(14453): 	at com.osfans.trime.ime.core.Trime$$ExternalSyntheticLambda0.onPrimaryClipChanged(Unknown Source:6)
E/CustomActivityOnCrash(14453): 	at android.content.ClipboardManager.reportPrimaryClipChanged(ClipboardManager.java:250)
E/CustomActivityOnCrash(14453): 	at android.content.ClipboardManager$1.lambda$dispatchPrimaryClipChanged$0$ClipboardManager$1(ClipboardManager.java:62)
E/CustomActivityOnCrash(14453): 	at android.content.-$$Lambda$ClipboardManager$1$hQk8olbGAgUi4WWNG4ZuDZsM39s.run(Unknown Source:2)
E/CustomActivityOnCrash(14453): 	at android.os.Handler.handleCallback(Handler.java:938)
E/CustomActivityOnCrash(14453): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/CustomActivityOnCrash(14453): 	at android.os.Looper.loop(Looper.java:223)
E/CustomActivityOnCrash(14453): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
E/CustomActivityOnCrash(14453): 	at java.lang.reflect.Method.invoke(Native Method)
E/CustomActivityOnCrash(14453): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/CustomActivityOnCrash(14453): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/CustomActivityOnCrash(14453): Failed when resolving the restart activity class via getLaunchIntentForPackage, stack trace follows!
E/CustomActivityOnCrash(14453): java.lang.ClassNotFoundException: com.osfans.trime.PrefLauncherAlias
E/CustomActivityOnCrash(14453): 	at java.lang.Class.classForName(Native Method)
E/CustomActivityOnCrash(14453): 	at java.lang.Class.forName(Class.java:454)
E/CustomActivityOnCrash(14453): 	at java.lang.Class.forName(Class.java:379)
E/CustomActivityOnCrash(14453): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash.getLauncherActivity(CustomActivityOnCrash.java:648)
E/CustomActivityOnCrash(14453): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash.guessRestartActivityClass(CustomActivityOnCrash.java:602)
E/CustomActivityOnCrash(14453): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash.lambda$install$0(CustomActivityOnCrash.java:177)
E/CustomActivityOnCrash(14453): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash$$ExternalSyntheticLambda0.uncaughtException(Unknown Source:2)
E/CustomActivityOnCrash(14453): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
E/CustomActivityOnCrash(14453): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
E/CustomActivityOnCrash(14453): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
E/CustomActivityOnCrash(14453): Caused by: java.lang.ClassNotFoundException: com.osfans.trime.PrefLauncherAlias
E/CustomActivityOnCrash(14453): 	... 10 more
I/Process (14453): Sending signal. PID: 14453 SIG: 9
```

**Comment by linsui** [comment]
The situation gets worse... Now everytime I copy something I'm forced to the Trime crash log.

**Comment by linsui** [comment]
Thanks!
