### ISSUE TITLE
点击"管理收藏夹内容"会崩溃

### ISSUE THREAD

**Issue by FanXiangTM** [osfans/trime#931]
点击：其它设置→管理收藏夹内容 就会崩溃

日志：

--------- Build Info
Builder: null
Build Time: 2022-11-03 21:49 UTC
Build Version Name: v3.2.9-0-ga34a9c3
Git Hash: a34a9c3
Git Branch: null
Git Repo: https://github.com/osfans/trime
--------- Device Info
App Package Name: com.osfans.trime
App Version Name: 3.2.9
App Version Code: 20221101
OS Name: GLK-AL00 2.0.0.270(C00E230R3P5)
OS Version: 4.14.116 (102.0.0.270C00)
OS API Level: 29
Device: HWGLK
Model (product): GLK-AL00 (GLK-AL00)
Manufacturer: HUAWEI
Tags: release-keys
Screen Size: 1080 x 2310
Screen Density: 3.0
Screen orientation: Portrait
--------- beginning of main
E/libc    (16959): Access denied finding property "persist.device_config.runtime_native.use_app_image_startup_cache"
E/om.osfans.trim(16959): LoadAppImageStartupCache enabled : 1
I/om.osfans.trim(16959): Reinit property: dalvik.vm.checkjni= false
I/om.osfans.trim(16959): ReInitProperties: persist.vm.debug.dumpapi= false
E/om.osfans.trim(16959): Not starting debugger since process cannot load the jdwp agent.
--------- beginning of system
D/ActivityThread(16959): Attach thread to application
I/ActivityThread(16959): Init compatible state: true
D/HwFrameworkSecurityPartsFactory(16959): HwFrameworkSecurityPartsFactory in.
I/HwFrameworkSecurityPartsFactory(16959): add HwFrameworkSecurityPartsFactory to memory.
E/BehaviorCollectManager(16959): Fail to acquire dataAnalyzerService...
D/ApplicationLoaders(16959): createClassLoader zip: /data/app/com.osfans.trime-dwU3FS2dRpIsXOqwhxI2Lw==/base.apk librarySearchPath: /data/app/com.osfans.trime-dwU3FS2dRpIsXOqwhxI2Lw==/lib/arm64:/data/app/com.osfans.trime-dwU3FS2dRpIsXOqwhxI2Lw==/base.apk!/lib/arm64-v8a libraryPermittedPath: /data/user/0/com.osfans.trime parent: java.lang.BootClassLoader@4e13d7e targetSdkVersion: 29 isBundled: false classLoaderName: null sharedLibraries: null
I/HwApiCacheMangerEx(16959): apicache path=/storage/emulated/0 state=mounted key=com.osfans.trime#10299#256
I/HwApiCacheMangerEx(16959): need clear apicache,because volumes changed,oldCnt=0 newCnt=1
I/HwApiCacheMangerEx(16959): apicache path=/storage/emulated/0 state=mounted key=com.osfans.trime#10299#0
I/HwApiCacheMangerEx(16959): need clear apicache,because volumes changed,oldCnt=1 newCnt=1
I/CustomActivityOnCrash(16959): CustomActivityOnCrash has been installed.
E/AwareLog(16959): AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@671e9dd
I/HwPartIawareFactory(16959): add android.common.HwPartIawareFactoryImpl to memory.
I/AwareBitmapCacher(16959): init processName:com.osfans.trime pid=16959 uid=10299
I/HwApiCacheMangerEx(16959): apicache path=/storage/emulated/0 state=mounted key=com.osfans.trime#10299#256
I/HwApiCacheMangerEx(16959): need clear apicache,because volumes changed,oldCnt=1 newCnt=1
I/HwApiCacheMangerEx(16959): apicache path=/storage/emulated/0 state=mounted key=com.osfans.trime#10299#0
I/HwApiCacheMangerEx(16959): need clear apicache,because volumes changed,oldCnt=1 newCnt=1
I/HwApiCacheMangerEx(16959): apicache path=/storage/emulated/0 state=mounted key=com.osfans.trime#10299#256
I/HwApiCacheMangerEx(16959): need clear apicache,because volumes changed,oldCnt=1 newCnt=1
I/HwTypeface(16959): updateFont: scale=1.0
D/SystemFonts(16959): areFontsVariable: script=Hans
I/ActivityThread(16959): finishPreloaded preloadStatus 0
I/Icon_Cache(16959): add:2131230720#me.ag2s.tts
I/TextToSpeech(16959): Sucessfully bound to me.ag2s.tts
I/HwApiCacheMangerEx(16959): apicache path=/storage/emulated/0 state=mounted key=com.osfans.trime#10299#0
I/HwApiCacheMangerEx(16959): need clear apicache,because volumes changed,oldCnt=1 newCnt=1
I/HwApiCacheMangerEx(16959): apicache path=/storage/emulated/0 state=mounted key=com.osfans.trime#10299#256
I/HwApiCacheMangerEx(16959): need clear apicache,because volumes changed,oldCnt=1 newCnt=1
I/System.out(16959):  144 144 144 144
I/System.out(16959):  155 155 155 155
I/System.out(16959):  144 144 144 144
I/System.out(16959):  155 155 155 155
I/System.out(16959):  144 144 144 144
I/System.out(16959):  155 155 155 155
I/System.out(16959):  78 118 118 118 118
I/System.out(16959):  84 127 127 127 129
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  102 90 90 90 90 90
I/System.out(16959):  106 93 93 93 93 97
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  78 90 90 90 90 90
I/System.out(16959):  83 96 96 96 96 101
I/System.out(16959):  72 72 72 72 72 72 72
I/System.out(16959):  77 77 77 77 77 77 80
I/System.out(16959):  72 72 72 72 72 72 72
I/System.out(16959):  77 77 77 77 77 77 80
I/System.out(16959):  72 72 72 72 72 72 72
I/System.out(16959):  77 77 77 77 77 77 80
I/System.out(16959):  72 72 72 72 72 72 72
I/System.out(16959):  77 77 77 77 77 77 80
I/System.out(16959):  72 72 72 72 72 72 72
I/System.out(16959):  77 77 77 77 77 77 80
I/System.out(16959):  72 72 72 72 72 72 72
I/System.out(16959):  77 77 77 77 77 77 80
I/System.out(16959):  118 118 118 118 79
I/System.out(16959):  127 127 127 127 86
I/RmeSchedManager(16959): init Rme, version is: v1.0
I/RmeSchedManager(16959): init Rme, version is: v1.0
I/RtgSchedEvent(16959): current pid:16959 AppType:-1
I/DecorView[InputMethod](16959): pkgName:com.osfans.trime old windowMode:0 new windoMode:1, isFixedSize:false
I/TextToSpeech(16959): Connected to ComponentInfo{me.ag2s.tts/me.ag2s.tts.services.TTSService}
W/ActivityThread(16959): handleWindowVisibility: no activity for token android.os.BinderProxy@e3f5be7
D/OpenGLRenderer(16959): disableOutlineDraw is true
I/OpenGLRenderer(16959): RenderThread: progress name = [com.osfans.trime], viewCornerType = 0
I/iGraphics(16959): [0020080c] pn: com.osfans.trime, p: 16959
I/iGraphics(16959): [0030080c] no spt app: com.osfans.trime
I/TextToSpeech(16959): Set up connection to ComponentInfo{me.ag2s.tts/me.ag2s.tts.services.TTSService}
V/ActivityThread(16959): callActivityOnCreate
I/DecorView[](16959): pkgName:com.osfans.trime old windowMode:0 new windoMode:1, isFixedSize:false
D/ActivityThread(16959): add activity client record, r= ActivityRecord{c23439b token=android.os.BinderProxy@e3f5be7 {com.osfans.trime/com.osfans.trime.PrefLauncherAlias}} token= android.os.BinderProxy@e3f5be7
I/OverScrollerOptimization(16959): start init SmartSlideOverScroller and get the overscroller config
I/OverScrollerOptimization(16959): get the overscroller config
D/MouseWheelSynthesizer(16959): mMoveStepInDp: 64, mMoveStepInPixel: 192, mUpTimeDelayed: 100
D/ViewRootImpl(16959): ViewRootImpl mIsInProductivePCDisplay: false
I/HwPartPowerOfficeFactory(16959): add HwPartPowerOfficeFactoryImpl to memory.
I/DecorView[](16959): pkgName:com.osfans.trime old windowMode:1 new windoMode:1, isFixedSize:false
D/InputEventReceiver(16959): dispatchInputInterval 1000000
I/RmeSchedManager(16959): init Rme, version is: v1.0
I/RtgSchedEvent(16959): current pid:16959 AppType:-1
D/InputEventReceiver(16959): dispatchInputInterval 1000000
E/HwViewGroupImpl(16959): parse speed value length error
D/MouseWheelSynthesizer(16959): mMoveStepInDp: 64, mMoveStepInPixel: 192, mUpTimeDelayed: 100
D/ViewRootImpl(16959): ViewRootImpl mIsInProductivePCDisplay: false
D/InputEventReceiver(16959): dispatchInputInterval 1000000
D/OpenGLRenderer(16959): disableOutlineDraw is true
D/HiTouch_PressGestureDetector(16959): onAttached, package=com.osfans.trime, windowType=1, mIsHiTouchRestricted=false
D/mali_winsys(16959): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
W/Gralloc3(16959): mapper 3.x is not supported
D/mali_winsys(16959): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer(16959): disableOutlineDraw is true
I/HwViewRootImpl(16959): removeInvalidNode jank list is null
D/DecorView(16959): showOrHideHighlightView: hasFocus=true; winMode=1; isMrgNull=true
W/InputMethodManager(16959): startInputReason = 1
W/HwRemoteInputMethodManager(16959): isCasting false because IHwDistributedWindowManager is invalid.
D/InputEventReceiver(16959): dispatchInputInterval 1000000
W/InputMethodManager(16959): startInputReason = 5
D/AwareBitmapCacher(16959): handleInit switch not opened pid=16959
I/ViewRootImpl(16959): dispatchDetachedFromWindow in doDie
W/libEGL  (16959): EGLNativeWindowType 0x73307151d0 disconnect failed
W/DisplayEventDispatcher(16959): dispatcher 0x73aacdcf40 ~ ignoring unknown event type 0x736f6674
I/Hwaps   (16959): APS: EventAnalyzed: initAPS: version is 11.0.0.4
D/Hwaps   (16959): Fpsrequest create,type:EXACTLY_IDENTIFY
D/Hwaps   (16959): Fpsrequest create,type:EXACTLY_IDENTIFY
D/Hwaps   (16959): Fpsrequest create,type:OPENGL_SETTING
D/Hwaps   (16959): FpsController create
D/Hwaps   (16959): APS: EventAnalyzed: reInitFpsPara :mBaseFps = 60; mMaxFps = 60
W/Settings(16959): Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
V/HiTouch_HiTouchSensor(16959): User setup is finished.
W/HwApsManager(16959): HwApsManagerService, registerCallback, start !
D/Hwaps   (16959): APS: EventAnalyzed: registerCallbackInApsManagerService, mPkgName:com.osfans.trime; result = true
V/AudioManager(16959): querySoundEffectsEnabled...
W/HwRemoteInputMethodManager(16959): isCasting false because IHwDistributedWindowManager is invalid.
I/HwViewRootImpl(16959): removeInvalidNode all the node in jank list is out of time
E/InputMethodManager(16959): closeCurrentInput
D/HwRemoteInputMethodManager(16959): hideRemoteSoftInput called.
W/HwRemoteInputMethodManager(16959): isCasting false because IHwDistributedWindowManager is invalid.
W/HiTouch_PressGestureDetector(16959): Touch pointer move a lot. The moving distance of X is:13.987061, limit is:60The moving distance of Y is:133.94214, limit is:60
V/InputMethodManager(16959): dispatchInputEvent
V/InputMethodManager(16959): dispatchInputEvent
V/AudioManager(16959): querySoundEffectsEnabled...
W/HiTouch_PressGestureDetector(16959): Touch pointer move a lot. The moving distance of X is:8.620056, limit is:60The moving distance of Y is:91.380615, limit is:60
V/AudioManager(16959): querySoundEffectsEnabled...
W/ActivityThread(16959): handleWindowVisibility: no activity for token android.os.BinderProxy@9455966
V/ActivityThread(16959): callActivityOnCreate
I/DecorView[](16959): pkgName:com.osfans.trime old windowMode:0 new windoMode:1, isFixedSize:false
E/CustomActivityOnCrash(16959): App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
E/CustomActivityOnCrash(16959): android.database.sqlite.SQLiteException: Can't downgrade database from version 4 to 3
E/CustomActivityOnCrash(16959): 	at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:560)
E/CustomActivityOnCrash(16959): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:434)
E/CustomActivityOnCrash(16959): 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:332)
E/CustomActivityOnCrash(16959): 	at com.osfans.trime.data.db.CollectionDao.getAllSimpleBean(CollectionDao.java:79)
E/CustomActivityOnCrash(16959): 	at com.osfans.trime.ui.main.LiquidKeyboardActivity$onCreate$3$1.invokeSuspend(LiquidKeyboardActivity.kt:60)
E/CustomActivityOnCrash(16959): 	at com.osfans.trime.ui.main.LiquidKeyboardActivity$onCreate$3$1.invoke(Unknown Source:8)
E/CustomActivityOnCrash(16959): 	at com.osfans.trime.ui.main.LiquidKeyboardActivity$onCreate$3$1.invoke(Unknown Source:2)
E/CustomActivityOnCrash(16959): 	at com.osfans.trime.util.DialogUtilsKt$withLoadingDialog$1.invokeSuspend(DialogUtils.kt:61)
E/CustomActivityOnCrash(16959): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
E/CustomActivityOnCrash(16959): 	at com.osfans.trime.util.DialogUtilsKt.withLoadingDialog(DialogUtils.kt:60)
E/CustomActivityOnCrash(16959): 	at com.osfans.trime.util.DialogUtilsKt.withLoadingDialog$default(DialogUtils.kt:49)
E/CustomActivityOnCrash(16959): 	at com.osfans.trime.ui.main.LiquidKeyboardActivity.onCreate(LiquidKeyboardActivity.kt:56)
E/CustomActivityOnCrash(16959): 	at android.app.Activity.performCreate(Activity.java:8214)
E/CustomActivityOnCrash(16959): 	at android.app.Activity.performCreate(Activity.java:8202)
E/CustomActivityOnCrash(16959): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
E/CustomActivityOnCrash(16959): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4033)
E/CustomActivityOnCrash(16959): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
E/CustomActivityOnCrash(16959): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
E/CustomActivityOnCrash(16959): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
E/CustomActivityOnCrash(16959): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
E/CustomActivityOnCrash(16959): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
E/CustomActivityOnCrash(16959): 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/CustomActivityOnCrash(16959): 	at android.os.Looper.loop(Looper.java:219)
E/CustomActivityOnCrash(16959): 	at android.app.ActivityThread.main(ActivityThread.java:8668)
E/CustomActivityOnCrash(16959): 	at java.lang.reflect.Method.invoke(Native Method)
E/CustomActivityOnCrash(16959): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/CustomActivityOnCrash(16959): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
E/CustomActivityOnCrash(16959): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@245b661, Dispatchers.Main.immediate]
E/CustomActivityOnCrash(16959): Failed when resolving the restart activity class via getLaunchIntentForPackage, stack trace follows!
E/CustomActivityOnCrash(16959): java.lang.ClassNotFoundException: com.osfans.trime.PrefLauncherAlias
E/CustomActivityOnCrash(16959): 	at java.lang.Class.classForName(Native Method)
E/CustomActivityOnCrash(16959): 	at java.lang.Class.forName(Class.java:454)
E/CustomActivityOnCrash(16959): 	at java.lang.Class.forName(Class.java:379)
E/CustomActivityOnCrash(16959): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash.getLauncherActivity(CustomActivityOnCrash.java:648)
E/CustomActivityOnCrash(16959): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash.guessRestartActivityClass(CustomActivityOnCrash.java:602)
E/CustomActivityOnCrash(16959): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash.lambda$install$0(CustomActivityOnCrash.java:177)
E/CustomActivityOnCrash(16959): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash$$ExternalSyntheticLambda0.uncaughtException(Unknown Source:2)
E/CustomActivityOnCrash(16959): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
E/CustomActivityOnCrash(16959): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:61)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:196)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:906)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:828)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
E/CustomActivityOnCrash(16959): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
E/CustomActivityOnCrash(16959): 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
E/CustomActivityOnCrash(16959): 	at com.osfans.trime.util.DialogUtilsKt.withLoadingDialog(DialogUtils.kt:60)
E/CustomActivityOnCrash(16959): 	at com.osfans.trime.util.DialogUtilsKt.withLoadingDialog$default(DialogUtils.kt:49)
E/CustomActivityOnCrash(16959): 	at com.osfans.trime.ui.main.LiquidKeyboardActivity.onCreate(LiquidKeyboardActivity.kt:56)
E/CustomActivityOnCrash(16959): 	at android.app.Activity.performCreate(Activity.java:8214)
E/CustomActivityOnCrash(16959): 	at android.app.Activity.performCreate(Activity.java:8202)
E/CustomActivityOnCrash(16959): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
E/CustomActivityOnCrash(16959): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4033)
E/CustomActivityOnCrash(16959): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
E/CustomActivityOnCrash(16959): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
E/CustomActivityOnCrash(16959): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
E/CustomActivityOnCrash(16959): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
E/CustomActivityOnCrash(16959): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
E/CustomActivityOnCrash(16959): 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/CustomActivityOnCrash(16959): 	at android.os.Looper.loop(Looper.java:219)
E/CustomActivityOnCrash(16959): 	at android.app.ActivityThread.main(ActivityThread.java:8668)
E/CustomActivityOnCrash(16959): 	at java.lang.reflect.Method.invoke(Native Method)
E/CustomActivityOnCrash(16959): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/CustomActivityOnCrash(16959): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
E/CustomActivityOnCrash(16959): Caused by: java.lang.ClassNotFoundException: com.osfans.trime.PrefLauncherAlias
E/CustomActivityOnCrash(16959): 	... 45 more
I/Process (16959): Sending signal. PID: 16959 SIG: 9

**Comment by WhiredPlanck** [comment]
@FanXiangTM 这个版本 app 设置中的管理页面已经移除了相关功能，但由于提交时机的原因没有完全删除。要管理剪贴板、草稿箱和收藏夹的内容，请在液态键盘的相应键盘中直接长按条目进行置顶/取消置顶、收藏和删除（全部）。
