### ISSUE TITLE
切换至其他输入法时崩溃

### ISSUE THREAD

**Issue by mytbk** [osfans/trime#968]
```
App Package Name: com.osfans.trime
App Version Name: 3.2.11
App Version Code: 20230301
OS Name: lineage_gauguin-userdebug 12 SQ3A.220705.004 a0168f5fbc
OS Version: 4.19.113-perf-g17320b2c10e9 (a0168f5fbc)
OS API Level: 32
Device: gauguinpro
Model (product): M2007J17C (lineage_gauguin)
Manufacturer: Xiaomi
Tags: release-keys
Screen Size: 1080 x 2400
Screen Density: 2.75
Screen orientation: Portrait
--------- beginning of main
W/TextToSpeech(28937): stop failed: not bound to TTS engine
D/AndroidRuntime(28937): Shutting down VM
--------- beginning of crash
E/AndroidRuntime(28937): FATAL EXCEPTION: main
E/AndroidRuntime(28937): Process: com.osfans.trime, PID: 28937
E/AndroidRuntime(28937): java.lang.RuntimeException: Unable to stop service com.osfans.trime.TrimeImeService@3c3be2c: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.osfans.trime.ime.keyboard.InputFeedbackManager.releaseSoundPool()' on a null object reference
E/AndroidRuntime(28937): 	at android.app.ActivityThread.handleStopService(ActivityThread.java:4756)
E/AndroidRuntime(28937): 	at android.app.ActivityThread.access$2100(ActivityThread.java:256)
E/AndroidRuntime(28937): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
E/AndroidRuntime(28937): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(28937): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(28937): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(28937): 	at android.app.ActivityThread.main(ActivityThread.java:7870)
E/AndroidRuntime(28937): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28937): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(28937): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(28937): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.osfans.trime.ime.keyboard.InputFeedbackManager.releaseSoundPool()' on a null object reference
E/AndroidRuntime(28937): 	at com.osfans.trime.ime.core.Trime.onFinishInputView(Trime.java:872)
E/AndroidRuntime(28937): 	at android.inputmethodservice.InputMethodService.finishViews(InputMethodService.java:2341)
E/AndroidRuntime(28937): 	at android.inputmethodservice.InputMethodService.doFinishInput(InputMethodService.java:2432)
E/AndroidRuntime(28937): 	at android.inputmethodservice.InputMethodService.onDestroy(InputMethodService.java:1429)
E/AndroidRuntime(28937): 	at com.osfans.trime.ime.lifecycle.LifecycleInputMethodService.onDestroy(LifecycleInputMethodService.kt:41)
E/AndroidRuntime(28937): 	at com.osfans.trime.ime.core.Trime.onDestroy(Trime.java:603)
E/AndroidRuntime(28937): 	at android.app.ActivityThread.handleStopService(ActivityThread.java:4736)
E/AndroidRuntime(28937): 	... 9 more
E/CustomActivityOnCrash(28937): App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
E/CustomActivityOnCrash(28937): java.lang.RuntimeException: Unable to stop service com.osfans.trime.TrimeImeService@3c3be2c: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.osfans.trime.ime.keyboard.InputFeedbackManager.releaseSoundPool()' on a null object reference
E/CustomActivityOnCrash(28937): 	at android.app.ActivityThread.handleStopService(ActivityThread.java:4756)
E/CustomActivityOnCrash(28937): 	at android.app.ActivityThread.access$2100(ActivityThread.java:256)
E/CustomActivityOnCrash(28937): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
E/CustomActivityOnCrash(28937): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/CustomActivityOnCrash(28937): 	at android.os.Looper.loopOnce(Looper.java:201)
E/CustomActivityOnCrash(28937): 	at android.os.Looper.loop(Looper.java:288)
E/CustomActivityOnCrash(28937): 	at android.app.ActivityThread.main(ActivityThread.java:7870)
E/CustomActivityOnCrash(28937): 	at java.lang.reflect.Method.invoke(Native Method)
E/CustomActivityOnCrash(28937): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/CustomActivityOnCrash(28937): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/CustomActivityOnCrash(28937): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.osfans.trime.ime.keyboard.InputFeedbackManager.releaseSoundPool()' on a null object reference
E/CustomActivityOnCrash(28937): 	at com.osfans.trime.ime.core.Trime.onFinishInputView(Trime.java:872)
E/CustomActivityOnCrash(28937): 	at android.inputmethodservice.InputMethodService.finishViews(InputMethodService.java:2341)
E/CustomActivityOnCrash(28937): 	at android.inputmethodservice.InputMethodService.doFinishInput(InputMethodService.java:2432)
E/CustomActivityOnCrash(28937): 	at android.inputmethodservice.InputMethodService.onDestroy(InputMethodService.java:1429)
E/CustomActivityOnCrash(28937): 	at com.osfans.trime.ime.lifecycle.LifecycleInputMethodService.onDestroy(LifecycleInputMethodService.kt:41)
E/CustomActivityOnCrash(28937): 	at com.osfans.trime.ime.core.Trime.onDestroy(Trime.java:603)
E/CustomActivityOnCrash(28937): 	at android.app.ActivityThread.handleStopService(ActivityThread.java:4736)
E/CustomActivityOnCrash(28937): 	... 9 more
E/CustomActivityOnCrash(28937): Failed when resolving the restart activity class via getLaunchIntentForPackage, stack trace follows!
E/CustomActivityOnCrash(28937): java.lang.ClassNotFoundException: com.osfans.trime.PrefLauncherAlias
E/CustomActivityOnCrash(28937): 	at java.lang.Class.classForName(Native Method)
E/CustomActivityOnCrash(28937): 	at java.lang.Class.forName(Class.java:454)
E/CustomActivityOnCrash(28937): 	at java.lang.Class.forName(Class.java:379)
E/CustomActivityOnCrash(28937): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash.getLauncherActivity(CustomActivityOnCrash.java:648)
E/CustomActivityOnCrash(28937): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash.guessRestartActivityClass(CustomActivityOnCrash.java:602)
E/CustomActivityOnCrash(28937): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash.lambda$install$0(CustomActivityOnCrash.java:177)
E/CustomActivityOnCrash(28937): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash$$ExternalSyntheticLambda0.uncaughtException(Unknown Source:2)
E/CustomActivityOnCrash(28937): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
E/CustomActivityOnCrash(28937): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
E/CustomActivityOnCrash(28937): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2200)
E/CustomActivityOnCrash(28937): Caused by: java.lang.ClassNotFoundException: com.osfans.trime.PrefLauncherAlias
E/CustomActivityOnCrash(28937): 	... 10 more
I/Process (28937): Sending signal. PID: 28937 SIG: 9
```

**Comment by wxyzh** [comment]
与 #956 相同
https://github.com/osfans/trime/commit/a3e27a5235e79757945754d2331f468b23e8c5e8 已经修复

**Comment by mytbk** [comment]
哦，是同一个问题。
