### ISSUE TITLE
3.2.11 Crash when display keyboard, even all new install

### ISSUE THREAD

**Issue by universorum** [osfans/trime#989]
**Describe the bug**
Fail to init keyboard

**To Reproduce**
Uninstall Trime (if exists)
Remove /sdcard/rime (if exists)
Install Trime
Launch App, init with app guide
exit, launch any (other) app and try to type something

**Log**
```
App Package Name: com.osfans.trime
App Version Name: 3.2.11
App Version Code: 20230301
OS Name: TQ2A.230305.008.E1.2023032600
OS Version: 5.10.169-android13-4-g1169069917cb (2023032600)
OS API Level: 33
Device: oriole
Model (product): Pixel 6 (oriole)
Manufacturer: Google
Tags: release-keys
Screen Size: 1080 x 2400
Screen Density: 2.625
Screen orientation: Portrait
--------- beginning of main
D/AndroidRuntime( 4934): Shutting down VM
--------- beginning of crash
E/AndroidRuntime( 4934): FATAL EXCEPTION: main
E/AndroidRuntime( 4934): Process: com.osfans.trime, PID: 4934
E/AndroidRuntime( 4934): android.view.InflateException: Binary XML file line #14 in com.osfans.trime:layout/input_root: Binary XML file line #16 in com.osfans.trime:layout/tab_bar: Error inflating class com.osfans.trime.ime.symbol.TabView
E/AndroidRuntime( 4934): Caused by: android.view.InflateException: Binary XML file line #16 in com.osfans.trime:layout/tab_bar: Error inflating class com.osfans.trime.ime.symbol.TabView
E/AndroidRuntime( 4934): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 4934): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
E/AndroidRuntime( 4934): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
E/AndroidRuntime( 4934): 	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
E/AndroidRuntime( 4934): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
E/AndroidRuntime( 4934): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
E/AndroidRuntime( 4934): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
E/AndroidRuntime( 4934): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
E/AndroidRuntime( 4934): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
E/AndroidRuntime( 4934): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
E/AndroidRuntime( 4934): 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
E/AndroidRuntime( 4934): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
E/AndroidRuntime( 4934): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
E/AndroidRuntime( 4934): 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
E/AndroidRuntime( 4934): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
E/AndroidRuntime( 4934): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
E/AndroidRuntime( 4934): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
E/AndroidRuntime( 4934): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
E/AndroidRuntime( 4934): 	at com.osfans.trime.databinding.InputRootBinding.inflate(InputRootBinding.java:51)
E/AndroidRuntime( 4934): 	at com.osfans.trime.databinding.InputRootBinding.inflate(InputRootBinding.java:45)
E/AndroidRuntime( 4934): 	at com.osfans.trime.ime.core.Trime.onCreateInputView(Trime.java:723)
E/AndroidRuntime( 4934): 	at android.inputmethodservice.InputMethodService.updateInputViewShown(InputMethodService.java:2075)
E/AndroidRuntime( 4934): 	at android.inputmethodservice.InputMethodService.prepareWindow(InputMethodService.java:2646)
E/AndroidRuntime( 4934): 	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:2575)
E/AndroidRuntime( 4934): 	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:923)
E/AndroidRuntime( 4934): 	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInputWithToken(InputMethodService.java:897)
E/AndroidRuntime( 4934): 	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:232)
E/AndroidRuntime( 4934): 	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
E/AndroidRuntime( 4934): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 4934): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 4934): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 4934): 	at android.app.ActivityThread.main(ActivityThread.java:7891)
E/AndroidRuntime( 4934): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4934): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 4934): 	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
E/AndroidRuntime( 4934): 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
E/AndroidRuntime( 4934): 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
E/AndroidRuntime( 4934): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Integer com.osfans.trime.data.theme.Config$Colors.getColor(java.lang.String)' on a null object reference
E/AndroidRuntime( 4934): 	at com.osfans.trime.ime.symbol.TabView.reset(TabView.java:61)
E/AndroidRuntime( 4934): 	at com.osfans.trime.ime.symbol.TabView.<init>(TabView.java:95)
E/AndroidRuntime( 4934): 	... 36 more
E/CustomActivityOnCrash( 4934): App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
E/CustomActivityOnCrash( 4934): android.view.InflateException: Binary XML file line #14 in com.osfans.trime:layout/input_root: Binary XML file line #16 in com.osfans.trime:layout/tab_bar: Error inflating class com.osfans.trime.ime.symbol.TabView
E/CustomActivityOnCrash( 4934): Caused by: android.view.InflateException: Binary XML file line #16 in com.osfans.trime:layout/tab_bar: Error inflating class com.osfans.trime.ime.symbol.TabView
E/CustomActivityOnCrash( 4934): Caused by: java.lang.reflect.InvocationTargetException
E/CustomActivityOnCrash( 4934): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
E/CustomActivityOnCrash( 4934): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
E/CustomActivityOnCrash( 4934): 	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
E/CustomActivityOnCrash( 4934): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
E/CustomActivityOnCrash( 4934): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
E/CustomActivityOnCrash( 4934): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
E/CustomActivityOnCrash( 4934): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
E/CustomActivityOnCrash( 4934): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
E/CustomActivityOnCrash( 4934): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
E/CustomActivityOnCrash( 4934): 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
E/CustomActivityOnCrash( 4934): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
E/CustomActivityOnCrash( 4934): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
E/CustomActivityOnCrash( 4934): 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
E/CustomActivityOnCrash( 4934): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
E/CustomActivityOnCrash( 4934): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
E/CustomActivityOnCrash( 4934): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
E/CustomActivityOnCrash( 4934): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
E/CustomActivityOnCrash( 4934): 	at com.osfans.trime.databinding.InputRootBinding.inflate(InputRootBinding.java:51)
E/CustomActivityOnCrash( 4934): 	at com.osfans.trime.databinding.InputRootBinding.inflate(InputRootBinding.java:45)
E/CustomActivityOnCrash( 4934): 	at com.osfans.trime.ime.core.Trime.onCreateInputView(Trime.java:723)
E/CustomActivityOnCrash( 4934): 	at android.inputmethodservice.InputMethodService.updateInputViewShown(InputMethodService.java:2075)
E/CustomActivityOnCrash( 4934): 	at android.inputmethodservice.InputMethodService.prepareWindow(InputMethodService.java:2646)
E/CustomActivityOnCrash( 4934): 	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:2575)
E/CustomActivityOnCrash( 4934): 	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:923)
E/CustomActivityOnCrash( 4934): 	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInputWithToken(InputMethodService.java:897)
E/CustomActivityOnCrash( 4934): 	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:232)
E/CustomActivityOnCrash( 4934): 	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
E/CustomActivityOnCrash( 4934): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/CustomActivityOnCrash( 4934): 	at android.os.Looper.loopOnce(Looper.java:201)
E/CustomActivityOnCrash( 4934): 	at android.os.Looper.loop(Looper.java:288)
E/CustomActivityOnCrash( 4934): 	at android.app.ActivityThread.main(ActivityThread.java:7891)
E/CustomActivityOnCrash( 4934): 	at java.lang.reflect.Method.invoke(Native Method)
E/CustomActivityOnCrash( 4934): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/CustomActivityOnCrash( 4934): 	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
E/CustomActivityOnCrash( 4934): 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
E/CustomActivityOnCrash( 4934): 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
E/CustomActivityOnCrash( 4934): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Integer com.osfans.trime.data.theme.Config$Colors.getColor(java.lang.String)' on a null object reference
E/CustomActivityOnCrash( 4934): 	at com.osfans.trime.ime.symbol.TabView.reset(TabView.java:61)
E/CustomActivityOnCrash( 4934): 	at com.osfans.trime.ime.symbol.TabView.<init>(TabView.java:95)
E/CustomActivityOnCrash( 4934): 	... 36 more
E/CustomActivityOnCrash( 4934): Failed when resolving the restart activity class via getLaunchIntentForPackage, stack trace follows!
E/CustomActivityOnCrash( 4934): java.lang.ClassNotFoundException: com.osfans.trime.PrefLauncherAlias
E/CustomActivityOnCrash( 4934): 	at java.lang.Class.classForName(Native Method)
E/CustomActivityOnCrash( 4934): 	at java.lang.Class.forName(Class.java:454)
E/CustomActivityOnCrash( 4934): 	at java.lang.Class.forName(Class.java:379)
E/CustomActivityOnCrash( 4934): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash.getLauncherActivity(CustomActivityOnCrash.java:648)
E/CustomActivityOnCrash( 4934): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash.guessRestartActivityClass(CustomActivityOnCrash.java:602)
E/CustomActivityOnCrash( 4934): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash.lambda$install$0(CustomActivityOnCrash.java:177)
E/CustomActivityOnCrash( 4934): 	at cat.ereza.customactivityoncrash.CustomActivityOnCrash$$ExternalSyntheticLambda0.uncaughtException(Unknown Source:2)
E/CustomActivityOnCrash( 4934): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
E/CustomActivityOnCrash( 4934): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
E/CustomActivityOnCrash( 4934): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
E/CustomActivityOnCrash( 4934): Caused by: java.lang.ClassNotFoundException: com.osfans.trime.PrefLauncherAlias
E/CustomActivityOnCrash( 4934): 	... 10 more
I/Process ( 4934): Sending signal. PID: 4934 SIG: 9
```

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6
 - OS: GrapheneOS 230305.008 (Android 13)
 - Build info: 
   ```
   Builder: null
   Build Time: 2023-03-04 06:11 UTC
   Build Version Name: v3.2.11-0-g46f3862c
   Git Hash: 46f3862c
   Git Branch: null
   Git Repo: https://github.com/osfans/trime
   ```
**Additional context**
App is install from F-Droid.

When try to display keyboard, App crash and display error screen.
after crash, I'm going to app's real-time log and it's same content

maybe related: #959

**Comment by wxyzh** [comment]
https://github.com/osfans/trime/issues/977#issuecomment-1481465826

**Comment by WhiredPlanck** [comment]
请看新版本有无此问题。Please take a look for new version.
每夜版/Nigntly Build：https://github.com/osfans/trime/releases/tag/nightly
